// SwipeLearn Pre-built Cards Database
// ~20 cards per topic × 9 topics × 5 difficulty levels
// Total: ~900 starter cards

const CARDS_DB = {

// ═══════════════════════════════════════════
// EXCEL
// ═══════════════════════════════════════════
excel: [
// Level 1 - Начальный
{l:1,title:"Автосумма",subtitle:"Быстрые вычисления",body:"Самый быстрый способ сложить числа. Выделите ячейку под столбцом чисел и нажмите Alt+=. Excel автоматически определит диапазон.",example:"Alt+= → =СУММ(A1:A10)",tip:"Работает и для строк — встаньте справа от чисел."},
{l:1,title:"Закрепление областей",subtitle:"Навигация",body:"При прокрутке больших таблиц шапка исчезает. Закрепите её: выделите строку ПОД шапкой → Вид → Закрепить области.",example:"Выделите A2 → Вид → Закрепить области → шапка в строке 1 зафиксирована",tip:"Для закрепления и строк и столбцов — выделите ячейку на пересечении."},
{l:1,title:"Быстрое заполнение",subtitle:"Ввод данных",body:"Двойной клик на маркере заполнения (чёрный крестик в углу ячейки) копирует формулу вниз до конца данных в соседнем столбце.",example:"Введите формулу в B2, наведите на правый нижний угол → двойной клик",tip:"Ctrl+D заполняет вниз выделенный диапазон."},
{l:1,title:"Формат ячеек",subtitle:"Форматирование",body:"Ctrl+1 — универсальная горячая клавиша для открытия окна форматирования. Здесь можно настроить числа, шрифт, границы, выравнивание.",example:"Ctrl+1 → вкладка Число → выберите формат",tip:"Для быстрого формата валюты: Ctrl+Shift+4, для процентов: Ctrl+Shift+5."},
{l:1,title:"СУММ / SUM",subtitle:"Базовые функции",body:"Складывает числа в диапазоне. Можно указывать несколько диапазонов через точку с запятой. Игнорирует текст и пустые ячейки.",example:"=СУММ(A1:A100) или =СУММ(A1:A10;C1:C10)",tip:"СУММ быстрее чем A1+A2+A3... и автоматически подстраивается при вставке строк."},
{l:1,title:"Фильтр данных",subtitle:"Анализ данных",body:"Ctrl+Shift+L включает автофильтр на выделенном диапазоне. Появляются выпадающие стрелки в шапке для фильтрации по значениям.",example:"Выделите таблицу → Ctrl+Shift+L → клик на стрелку в заголовке",tip:"Фильтр не удаляет данные — только скрывает строки. Ctrl+Shift+L снова — убрать фильтр."},
{l:1,title:"Перенос текста",subtitle:"Форматирование",body:"Длинный текст выходит за границы ячейки. Включите перенос: Главная → Перенос текста, и текст будет переноситься по строкам внутри ячейки.",example:"Выделите ячейки → Alt+H → W (или кнопка на ленте)",tip:"Alt+Enter вставляет перенос строки вручную внутри ячейки."},
{l:1,title:"Ctrl+Home / Ctrl+End",subtitle:"Навигация",body:"Ctrl+Home мгновенно перемещает к ячейке A1. Ctrl+End — к последней использованной ячейке листа. Экономит время в больших таблицах.",example:"В любом месте листа → Ctrl+Home → вы в A1",tip:"Ctrl+стрелка перемещает до конца непрерывного блока данных."},
{l:1,title:"Копирование листов",subtitle:"Работа с листами",body:"Зажмите Ctrl и перетащите ярлычок листа — создастся копия. Полезно для создания шаблонов месячных отчётов.",example:"Ctrl + перетащите ярлычок листа → появится «Лист1 (2)»",tip:"Правый клик на ярлычке → Переместить/Скопировать — для копирования между книгами."},
{l:1,title:"СЧЁТЗ / COUNTA",subtitle:"Базовые функции",body:"Считает количество непустых ячеек в диапазоне. В отличие от СЧЁТ (COUNT), считает и текст, и числа, и даты.",example:"=СЧЁТЗ(A1:A100) → количество заполненных ячеек",tip:"СЧИТАТЬПУСТОТЫ(A1:A100) — обратная функция, считает пустые ячейки."},

// Level 2 - Базовый
{l:2,title:"ВПР / VLOOKUP",subtitle:"Функции поиска",body:"Ищет значение в первом столбце таблицы и возвращает данные из указанного столбца. Основа для связывания таблиц.",example:"=ВПР(A2;Справочник!A:D;3;ЛОЖЬ)\nИщет A2 в справочнике, возвращает 3-й столбец",tip:"Всегда ставьте ЛОЖЬ (точное совпадение). В новых версиях используйте XLOOKUP."},
{l:2,title:"ЕСЛИ / IF",subtitle:"Логические функции",body:"Проверяет условие и возвращает одно значение если истина, другое — если ложь. Основа любой логики в Excel.",example:"=ЕСЛИ(A1>1000;\"Крупный\";\"Мелкий\")\n=ЕСЛИ(B1=\"\";0;B1*C1)",tip:"Вложенные ЕСЛИ до 64 уровней, но лучше используйте ПЕРЕКЛЮЧ или ЕСЛИМН."},
{l:2,title:"Условное форматирование",subtitle:"Визуализация",body:"Автоматически меняет цвет ячеек по правилам. Идеально для выделения просроченных дат, отклонений, дубликатов.",example:"Главная → Условное форматирование → Правила выделения → Больше чем...",tip:"Используйте формулу в правиле для сложных условий: =И($A1>0;$B1<СЕГОДНЯ())"},
{l:2,title:"Абсолютные ссылки $",subtitle:"Формулы",body:"$ фиксирует строку или столбец при копировании формулы. $A$1 — полная фиксация, $A1 — фиксирован столбец, A$1 — строка.",example:"=A1*$B$1 → при копировании вниз B1 не сдвинется\nF4 переключает режимы ссылок",tip:"F4 после клика на ячейку циклически переключает: A1→$A$1→A$1→$A1→A1"},
{l:2,title:"СУММЕСЛИ / SUMIF",subtitle:"Условные вычисления",body:"Суммирует ячейки, удовлетворяющие условию. Незаменима для быстрых итогов по категории без сводных таблиц.",example:"=СУММЕСЛИ(A:A;\"Москва\";C:C)\nСумма C где в A = «Москва»",tip:"СУММЕСЛИМН — для нескольких условий одновременно."},
{l:2,title:"Именованные диапазоны",subtitle:"Организация",body:"Вместо A1:D100 дайте диапазону имя — формулы станут понятнее: =СУММ(Продажи) вместо =СУММ(Лист2!C5:C500).",example:"Выделите диапазон → Поле имени (слева от строки формул) → введите имя → Enter",tip:"Ctrl+F3 — менеджер имён. Используйте в ВПР и СУММЕСЛИ для читаемости."},
{l:2,title:"Текст по столбцам",subtitle:"Обработка данных",body:"Разделяет содержимое одного столбца на несколько. Полезно для разбора ФИО, адресов, импортированных CSV-данных.",example:"Данные → Текст по столбцам → выберите разделитель (;) или фиксированную ширину",tip:"Также помогает исправить «числа-как-текст» — пропустите столбец через мастер."},
{l:2,title:"Сводные таблицы — основы",subtitle:"Анализ данных",body:"Мощнейший инструмент анализа. Перетаскивайте поля в области: строки, столбцы, значения, фильтры — мгновенные итоги.",example:"Выделите данные → Вставка → Сводная таблица → перетащите поля",tip:"Данные должны иметь заголовки, без пустых строк/столбцов. Обновление: правый клик → Обновить."},
{l:2,title:"СЦЕПИТЬ / CONCAT",subtitle:"Текстовые функции",body:"Соединяет текст из нескольких ячеек в одну строку. Оператор & — более гибкий аналог.",example:"=A1&\" \"&B1&\" \"&C1\n=СЦЕПИТЬ(A1;\" \";B1) — то же самое",tip:"ОБЪЕДИНИТЬ/TEXTJOIN удобнее для массивов: =ОБЪЕДИНИТЬ(\", \";ИСТИНА;A1:A10)"},
{l:2,title:"Быстрый анализ",subtitle:"Инструменты",body:"Выделите данные → появится иконка ⚡ в правом нижнем углу. Предлагает форматирование, диаграммы, итоги, таблицы, спарклайны.",example:"Выделите числовой столбец → ⚡ → Итоги → Нарастающий итог",tip:"Ctrl+Q — горячая клавиша для Быстрого анализа."},

// Level 3 - Средний
{l:3,title:"ИНДЕКС+ПОИСКПОЗ",subtitle:"Продвинутый поиск",body:"Замена ВПР без ограничений. ПОИСКПОЗ находит позицию, ИНДЕКС возвращает значение. Ищет в любом направлении.",example:"=ИНДЕКС(C:C;ПОИСКПОЗ(F1;A:A;0))\nНаходит F1 в столбце A, возвращает из C",tip:"Быстрее ВПР на больших данных. Работает влево — ВПР так не умеет."},
{l:3,title:"Таблицы Excel (Ctrl+T)",subtitle:"Структуры данных",body:"Превращает диапазон в умную таблицу. Автоматическое расширение, структурированные ссылки, автофильтр, строка итогов.",example:"Ctrl+T → =СУММ(tblSales[Revenue]) вместо =СУММ(D2:D1000)",tip:"В формулах используйте [@Column] для текущей строки: =[@Price]*[@Qty]"},
{l:3,title:"Проверка данных",subtitle:"Контроль ввода",body:"Ограничивает ввод в ячейки: выпадающие списки, числовые диапазоны, даты. Предотвращает ошибки ввода.",example:"Данные → Проверка данных → Список → введите значения через ; или укажите диапазон",tip:"Добавьте сообщение об ошибке и подсказку при выделении для удобства пользователей."},
{l:3,title:"СУММЕСЛИМН / SUMIFS",subtitle:"Множественные условия",body:"Суммирует по нескольким условиям одновременно. Диапазон суммирования идёт ПЕРВЫМ — в отличие от СУММЕСЛИ.",example:"=СУММЕСЛИМН(D:D;A:A;\"Москва\";B:B;\">\"&ДАТА(2024;1;1))\nСумма D где A=Москва и B>01.01.2024",tip:"Для дат используйте \">\"&ДАТА() — не текстовые строки дат."},
{l:3,title:"Power Query — Импорт",subtitle:"ETL",body:"Мощный инструмент для импорта и трансформации данных из файлов, папок, баз данных, API. Запросы обновляются одной кнопкой.",example:"Данные → Получить данные → Из файла → Из папки\nЗагрузит все файлы из папки",tip:"Все шаги трансформации записываются — можно редактировать и воспроизводить."},
{l:3,title:"ДВССЫЛ / INDIRECT",subtitle:"Динамические ссылки",body:"Превращает текстовую строку в ссылку на ячейку. Позволяет динамически формировать адреса ячеек и диапазонов.",example:"=ДВССЫЛ(\"Лист\"&A1&\"!B2\")\nЕсли A1=3, обращается к Лист3!B2",tip:"Используйте с проверкой данных для каскадных выпадающих списков."},
{l:3,title:"Массивы (Ctrl+Shift+Enter)",subtitle:"Формулы массивов",body:"Формулы, обрабатывающие несколько значений одновременно. В Microsoft 365 вводятся обычным Enter (динамические массивы).",example:"=СУММ(ЕСЛИ(A1:A10=\"Да\";B1:B10;0))\nCSE в старых версиях, просто Enter в 365",tip:"В Microsoft 365 используйте ФИЛЬТР, СОРТ, УНИК — это динамические массивы."},
{l:3,title:"Спарклайны",subtitle:"Микро-визуализация",body:"Миниатюрные диаграммы внутри ячейки. Показывают тренд рядом с данными без создания полноразмерного графика.",example:"Вставка → Спарклайны → Линия → выберите данные и ячейку для размещения",tip:"Настройте маркеры для максимума/минимума, чтобы выделить ключевые точки."},
{l:3,title:"ЕСЛИОШИБКА / IFERROR",subtitle:"Обработка ошибок",body:"Оборачивает формулу и возвращает альтернативное значение при ошибке вместо #Н/Д, #ЗНАЧ!, #ДЕЛ/0!",example:"=ЕСЛИОШИБКА(ВПР(A1;Данные!A:C;3;0);\"Не найдено\")",tip:"Не злоупотребляйте — она скрывает ВСЕ ошибки. Для конкретной: ЕСНД/IFNA."},
{l:3,title:"Группировка строк/столбцов",subtitle:"Организация",body:"Создаёт сворачиваемые уровни в таблице. Скрывайте детали, оставляя итоги видимыми.",example:"Выделите строки → Данные → Группировать → кнопки +/- и 1/2/3 слева",tip:"Данные → Промежуточные итоги автоматически группируют и добавляют формулы."},

// Level 4 - Продвинутый
{l:4,title:"Power Pivot",subtitle:"Модели данных",body:"Движок xVelocity для анализа миллионов строк. Связывает таблицы как в БД, создаёт вычисляемые меры на DAX.",example:"Power Pivot → Manage → Add to Data Model\nСоздайте связи между таблицами через диаграмму",tip:"Сводная на Power Pivot обращается к нескольким таблицам без ВПР."},
{l:4,title:"DAX — Основы",subtitle:"Язык формул",body:"Data Analysis Expressions — язык формул Power Pivot и Power BI. Меры вычисляются в контексте фильтров сводной таблицы.",example:"Total Sales:=SUMX(Sales;Sales[Qty]*Sales[Price])\nYoY:=CALCULATE([Total];SAMEPERIODLASTYEAR(Calendar[Date]))",tip:"Мера vs Вычисляемый столбец: мера считается в контексте, столбец — построчно."},
{l:4,title:"LAMBDA",subtitle:"Пользовательские функции",body:"Создаёт именованные пользовательские функции без VBA. Определите параметры и формулу один раз, используйте как обычную функцию.",example:"Имя: КонвертУSD, Формула: =LAMBDA(rub;rate;rub/rate)\nИспользование: =КонвертУSD(A1;B1)",tip:"Комбинируйте с MAP, REDUCE, SCAN для обработки массивов."},
{l:4,title:"ФИЛЬТР / FILTER",subtitle:"Динамические массивы",body:"Возвращает массив строк, соответствующих условию. Заменяет сложные формулы массивов и вспомогательные столбцы.",example:"=ФИЛЬТР(A2:D100;C2:C100>1000;\"Нет данных\")\nВсе строки где C > 1000",tip:"Комбинируйте с СОРТ: =СОРТ(ФИЛЬТР(A:D;C:C>1000);3;-1) — отфильтровать и отсортировать."},
{l:4,title:"Power Query — M язык",subtitle:"Продвинутый ETL",body:"Язык M — основа Power Query. Каждый шаг — выражение let...in. Позволяет создавать пользовательские функции и сложные трансформации.",example:"let\n  Src = Excel.CurrentWorkbook(){[Name=\"tbl\"]}[Content],\n  Filtered = Table.SelectRows(Src, each [Amount]>0)\nin\n  Filtered",tip:"Расширенный редактор (Alt) показывает полный код. Функции начинаются с заглавной: Table.AddColumn."},
{l:4,title:"Макет сводной таблицы",subtitle:"Отчётность",body:"Сводные таблицы поддерживают табличный макет, повтор подписей элементов, вычисляемые поля и элементы — для отчётов любой сложности.",example:"Конструктор → Макет отчёта → Показать в табличной форме\n+ Повторить все подписи элементов",tip:"Вычисляемое поле: Анализ → Поля, элементы → Вычисляемое поле."},
{l:4,title:"Условное форматирование формулой",subtitle:"Продвинутая визуализация",body:"Используйте собственные формулы для сложных правил выделения. Формула должна возвращать ИСТИНА/ЛОЖЬ.",example:"Выделить строку если просрочено:\n=$D1<СЕГОДНЯ() ($ перед столбцом, не перед строкой)\nПрименить ко всему диапазону строк",tip:"$ перед столбцом фиксирует его — правило проверяет один столбец, но красит всю строку."},
{l:4,title:"XLOOKUP",subtitle:"Современный поиск",body:"Замена ВПР/ГПР/ИНДЕКС+ПОИСКПОЗ. Ищет в любом направлении, поддерживает точное/приближённое совпадение и подстановочные знаки.",example:"=XLOOKUP(F1;A:A;C:C;\"Не найдено\";0;1)\nПоиск F1 в A, результат из C, 0=точное, 1=с начала",tip:"Последний аргумент: 1=сначала, -1=с конца, 2=бинарный поиск (для сортированных данных)."},
{l:4,title:"Пользовательские числовые форматы",subtitle:"Форматирование",body:"Создавайте свои форматы чисел через маску из 4 секций: положительные;отрицательные;ноль;текст.",example:"#,##0.00\" ₽\" — число с пробелами и рублём\n[Зелёный]#,##0;[Красный]-#,##0 — цвет по знаку\n0.0,,\" млн\" — деление на миллион",tip:"# — необязательная цифра, 0 — обязательная. Запятая в конце делит на 1000."},
{l:4,title:"Зависимости формул",subtitle:"Отладка",body:"Формулы → Влияющие/Зависимые ячейки рисует стрелки связей. Помогает понять структуру чужих файлов и найти ошибки.",example:"Ctrl+[ — перейти к влияющим ячейкам\nCtrl+] — перейти к зависимым\nФормулы → Убрать стрелки",tip:"Вычисление формул пошагово: Формулы → Вычислить формулу (F9 в строке формул для части)."},

// Level 5 - Экспертный
{l:5,title:"Office Scripts (TypeScript)",subtitle:"Автоматизация 365",body:"Замена VBA для облачного Excel. TypeScript-скрипты запускаются в Excel Online и через Power Automate для автоматизации.",example:"function main(workbook: ExcelScript.Workbook) {\n  let sheet = workbook.getActiveWorksheet();\n  let range = sheet.getRange(\"A1:D100\");\n  range.getFormat().autofitColumns();\n}",tip:"Office Scripts работают в облаке — можно запускать по расписанию через Power Automate."},
{l:5,title:"Динамический массив: REDUCE",subtitle:"Функциональное программирование",body:"Сворачивает массив в одно значение, применяя функцию-аккумулятор к каждому элементу. Аналог reduce() в JavaScript.",example:"=REDUCE(0;A1:A10;LAMBDA(acc;val;acc+val^2))\nСумма квадратов всех значений",tip:"REDUCE + VSTACK позволяет строить таблицы произвольной структуры."},
{l:5,title:"Кубические функции",subtitle:"OLAP",body:"КУБЗНАЧЕНИЕ, КУБЭЛЕМЕНТ и др. извлекают данные из модели Power Pivot напрямую в ячейки, минуя сводные таблицы.",example:"=КУБЗНАЧЕНИЕ(\"ThisWorkbookDataModel\";\n  \"[Measures].[Total Sales]\";\n  \"[Date].[Year].&[2024]\")",tip:"Позволяют создавать произвольные отчёты с нужным макетом — без ограничений сводных таблиц."},
{l:5,title:"Volatile vs Non-Volatile",subtitle:"Оптимизация",body:"Volatile-функции (СЕГОДНЯ, СЛУЧМЕЖДУ, ДВССЫЛ, СМЕЩ) пересчитываются при КАЖДОМ изменении книги, замедляя работу.",example:"ДВССЫЛ → замените на ИНДЕКС\nСМЕЩ → замените на ИНДЕКС\nТЕПЕРЬ → вычисляйте однократно в VBA",tip:"Формулы → Параметры вычислений → Вручную (F9 для пересчёта) при работе с тяжёлыми файлами."},
{l:5,title:"LET",subtitle:"Оптимизация формул",body:"Присваивает имена промежуточным вычислениям внутри формулы. Улучшает читаемость и производительность — вычисление однократно.",example:"=LET(\n  sales;СУММ(B:B);\n  costs;СУММ(C:C);\n  margin;(sales-costs)/sales;\n  ЕСЛИ(margin>0.2;\"Ок\";\"Низкая\")\n)",tip:"LET вычисляет каждую переменную ОДИН раз — если используете результат 5 раз, он не пересчитывается."},
{l:5,title:"Структурированные ссылки + DAX",subtitle:"Моделирование данных",body:"Комбинируйте Excel-таблицы (tbl*) с Power Pivot для создания полноценной аналитической модели без выгрузки в Power BI.",example:"Таблица tblFact связана с tblDim через Power Pivot\nМера: =CALCULATE(SUM(tblFact[Amount]);\n  FILTER(tblDim;tblDim[Region]=\"CIS\"))",tip:"Именованные таблицы автоматически расширяются — модель данных всегда актуальна."},
{l:5,title:"GROUPBY и PIVOTBY",subtitle:"Новейшие функции 365",body:"Встроенные функции группировки и пивотирования прямо в формулах. Создают мини-сводные без сводных таблиц.",example:"=GROUPBY(A2:A100;C2:C100;SUM)\nГруппирует A, суммирует C\n=PIVOTBY(A2:A100;B2:B100;C2:C100;SUM)",tip:"Доступны только в Microsoft 365 (канал Insiders). Результат — динамический массив."},
{l:5,title:"Custom Data Types",subtitle:"Типы данных",body:"Power Query может создавать пользовательские типы данных — одна ячейка содержит структурированный объект с полями.",example:"Power Query → Преобразование → Создать тип данных\nВ ячейке: =A1.Revenue, =A1.Country",tip:"Используйте для справочников — одна ячейка вместо нескольких столбцов."},
{l:5,title:"Формулы массивов + LET + LAMBDA",subtitle:"Продвинутые паттерны",body:"Комбинация LET для именования, LAMBDA для логики и MAP/REDUCE/SCAN для обработки создаёт функциональный стиль программирования в Excel.",example:"=LET(\n  data;A2:A100;\n  cleaned;FILTER(data;data<>\"\");\n  MAP(cleaned;LAMBDA(x;\n    IF(ISNUMBER(x);x*1.2;UPPER(x))))\n)",tip:"Это по сути функциональное программирование в ячейке — без VBA и скриптов."},
{l:5,title:"Производительность: 1M+ строк",subtitle:"Оптимизация",body:"Для больших данных: используйте Power Query для ETL, Power Pivot для модели, избегайте volatile-функций и целиковых столбцов (A:A).",example:"Плохо: =ВПР(A1;B:D;3;0) — сканирует 1М строк\nХорошо: =ВПР(A1;tblRef;3;0) — только данные таблицы",tip:"Бинарные форматы (.xlsb) на 50-75% меньше .xlsx и открываются быстрее."},
],

// ═══════════════════════════════════════════
// VBA
// ═══════════════════════════════════════════
vba: [
// Level 1
{l:1,title:"Sub процедура",subtitle:"Основы VBA",body:"Sub — базовый блок кода VBA. Записывается в модуле и запускается по кнопке, горячей клавише или из другого кода.",example:"Sub Приветствие()\n  MsgBox \"Привет, мир!\"\nEnd Sub",tip:"Alt+F11 открывает редактор VBA. Alt+F8 — список доступных макросов."},
{l:1,title:"Запись макроса",subtitle:"Первые шаги",body:"Вид → Макросы → Запись макроса. Excel записывает ваши действия как код VBA. Отличный способ изучить синтаксис.",example:"Запишите форматирование ячейки → остановите запись → Alt+F11 → изучите код",tip:"Записанный код избыточен — упрощайте его, удаляя ненужные свойства."},
{l:1,title:"MsgBox и InputBox",subtitle:"Диалоги",body:"MsgBox показывает сообщение. InputBox запрашивает ввод от пользователя. Базовые инструменты взаимодействия.",example:"Dim name As String\nname = InputBox(\"Ваше имя:\")\nMsgBox \"Привет, \" & name & \"!\"",tip:"MsgBox с кнопками: If MsgBox(\"Уверены?\", vbYesNo) = vbYes Then..."},
{l:1,title:"Переменные и типы",subtitle:"Основы языка",body:"Dim объявляет переменную. Основные типы: String (текст), Long (целое число), Double (дробное), Boolean (да/нет), Date.",example:"Dim count As Long\nDim price As Double\nDim name As String\ncount = 100\nprice = 99.95\nname = \"Товар\"",tip:"Добавьте Option Explicit в начало модуля — VBA потребует объявлять все переменные."},
{l:1,title:"Range и Cells",subtitle:"Работа с ячейками",body:"Range(\"A1\") обращается к ячейке по адресу. Cells(1,1) — по номеру строки и столбца. Cells удобнее в циклах.",example:"Range(\"A1\").Value = \"Текст\"\nCells(1, 1).Value = \"То же самое\"\nRange(\"A1:D10\").Font.Bold = True",tip:"Range(Cells(1,1), Cells(10,4)) — динамический диапазон через Cells."},
{l:1,title:"Цикл For...Next",subtitle:"Циклы",body:"Повторяет блок кода заданное количество раз. Переменная-счётчик автоматически увеличивается на каждой итерации.",example:"Dim i As Long\nFor i = 1 To 100\n  Cells(i, 2).Value = Cells(i, 1).Value * 2\nNext i",tip:"Step задаёт шаг: For i = 100 To 1 Step -1 — обратный цикл (важно при удалении строк)."},
{l:1,title:"With...End With",subtitle:"Оптимизация кода",body:"Группирует операции с одним объектом. Код короче и работает быстрее — объект вычисляется один раз.",example:"With Range(\"A1\")\n  .Value = \"Заголовок\"\n  .Font.Bold = True\n  .Font.Size = 14\n  .Interior.Color = vbYellow\nEnd With",tip:"With можно вкладывать друг в друга для вложенных объектов."},
{l:1,title:"Комментарии",subtitle:"Чистый код",body:"Апостроф ' начинает комментарий. Всё после него на строке игнорируется. Документируйте логику, не действия.",example:"' Плохо: Устанавливаем значение A1 в 5\n' Хорошо: Начальный остаток на счёте\nRange(\"A1\").Value = 5",tip:"Ctrl+Shift+C — закомментировать блок (если включена панель Edit)."},
{l:1,title:"Автозаполнение кода",subtitle:"Редактор VBA",body:"Ctrl+Space — автозаполнение. Ctrl+J — список свойств. F1 на ключевом слове — справка. Эти горячие клавиши ускоряют работу.",example:"Введите Range(\"A1\"). и нажмите Ctrl+J\nПоявится список всех свойств и методов",tip:"F5 — запуск, F8 — пошаговое выполнение, F9 — точка останова (breakpoint)."},
{l:1,title:"Sheets и Workbooks",subtitle:"Объектная модель",body:"Workbooks(\"Книга.xlsx\") — книга. Sheets(\"Лист1\") — лист. ThisWorkbook — книга с кодом. ActiveSheet — текущий лист.",example:"Sheets(\"Отчёт\").Range(\"A1\").Value = \"Готово\"\nThisWorkbook.Save\nWorkbooks.Open \"C:\\data.xlsx\"",tip:"Используйте кодовые имена листов (Sheet1 в проекте VBA) — они не меняются при переименовании."},

// Level 2
{l:2,title:"For Each",subtitle:"Циклы по коллекциям",body:"Перебирает каждый элемент коллекции: ячейки диапазона, листы книги, файлы. Безопаснее и читаемее For...Next для коллекций.",example:"Dim ws As Worksheet\nFor Each ws In ThisWorkbook.Sheets\n  ws.Range(\"A1\").Value = ws.Name\nNext ws",tip:"Для удаления элементов из коллекции используйте For...Next с обратным шагом (Step -1)."},
{l:2,title:"If...ElseIf...Else",subtitle:"Условия",body:"Ветвление кода по условиям. ElseIf позволяет проверять несколько условий последовательно.",example:"If score >= 90 Then\n  grade = \"A\"\nElseIf score >= 70 Then\n  grade = \"B\"\nElse\n  grade = \"C\"\nEnd If",tip:"Select Case удобнее для множества условий: Select Case score / Case Is >= 90 / Case 70 To 89..."},
{l:2,title:"Application.ScreenUpdating",subtitle:"Производительность",body:"Отключение обновления экрана ускоряет макросы в 5-100 раз. Всегда включайте обратно в конце и при ошибках.",example:"Sub FastMacro()\n  Application.ScreenUpdating = False\n  ' ... ваш код ...\n  Application.ScreenUpdating = True\nEnd Sub",tip:"Комбинируйте с Application.Calculation = xlCalculationManual для максимальной скорости."},
{l:2,title:"LastRow / LastCol",subtitle:"Определение границ данных",body:"Нахождение последней заполненной строки — одна из самых частых задач VBA. Используйте End(xlUp) от последней строки листа.",example:"Dim lastRow As Long\nlastRow = Cells(Rows.Count, 1).End(xlUp).Row\n' Или: lastRow = Range(\"A\" & Rows.Count).End(xlUp).Row",tip:"Для столбца: lastCol = Cells(1, Columns.Count).End(xlToLeft).Column"},
{l:2,title:"Массивы VBA",subtitle:"Структуры данных",body:"Чтение диапазона в массив и обратно — в 100+ раз быстрее, чем обращение к каждой ячейке по отдельности.",example:"Dim arr As Variant\narr = Range(\"A1:D10000\").Value ' читаем в массив\n' Обрабатываем arr(row, col)\nRange(\"A1:D10000\").Value = arr ' записываем обратно",tip:"Индексация массива из Range начинается с (1,1), не с (0,0)."},
{l:2,title:"Обработка ошибок On Error",subtitle:"Надёжный код",body:"On Error управляет поведением при ошибках. GoTo — переход к метке обработчика. Resume Next — пропуск ошибки.",example:"Sub SafeOpen()\n  On Error GoTo ErrHandler\n  Workbooks.Open \"C:\\data.xlsx\"\n  Exit Sub\nErrHandler:\n  MsgBox \"Файл не найден: \" & Err.Description\nEnd Sub",tip:"On Error Resume Next + проверка Err.Number — для ожидаемых ошибок (проверка существования)."},
{l:2,title:"Do While / Do Until",subtitle:"Условные циклы",body:"Цикл выполняется пока условие истинно (While) или пока не станет истинным (Until). Для неизвестного числа итераций.",example:"Dim i As Long: i = 1\nDo While Cells(i, 1).Value <> \"\"\n  Cells(i, 2).Value = UCase(Cells(i, 1).Value)\n  i = i + 1\nLoop",tip:"Остерегайтесь бесконечных циклов — всегда меняйте условие внутри цикла."},
{l:2,title:"Функция (Function)",subtitle:"Пользовательские функции",body:"Function возвращает значение и может использоваться как формула в ячейках Excel. UDF — User Defined Function.",example:"Function НДС(amount As Double) As Double\n  НДС = amount * 0.2\nEnd Function\n' В ячейке: =НДС(A1)",tip:"UDF не может менять другие ячейки или форматирование — только возвращать значение."},
{l:2,title:"String функции",subtitle:"Работа с текстом",body:"Left, Right, Mid — извлечение части текста. InStr — поиск подстроки. Len — длина. Replace — замена.",example:"Left(\"Привет\", 3)    ' → \"При\"\nInStr(\"Hello World\", \"World\")  ' → 7\nReplace(\"A-B-C\", \"-\", \"/\") ' → \"A/B/C\"",tip:"Like для паттернов: If name Like \"*ов\" Then — фамилии на -ов."},
{l:2,title:"Workbook Events",subtitle:"События",body:"Код в модуле ThisWorkbook/Sheet выполняется автоматически при событиях: открытие, сохранение, изменение ячейки.",example:"' В модуле ThisWorkbook:\nPrivate Sub Workbook_Open()\n  MsgBox \"Добро пожаловать!\"\nEnd Sub\n' В модуле Sheet1:\nPrivate Sub Worksheet_Change(ByVal Target As Range)\n  ' реакция на изменение\nEnd Sub",tip:"Target.Address в Worksheet_Change — адрес изменённой ячейки. Intersect проверяет попадание в диапазон."},

// Level 3
{l:3,title:"Dictionary объект",subtitle:"Структуры данных",body:"Словарь ключ-значение для быстрого поиска, подсчёта уникальных, группировки. Аналог HashMap/Dict из других языков.",example:"Dim dict As Object\nSet dict = CreateObject(\"Scripting.Dictionary\")\ndict(\"RUB\") = 92.5\ndict(\"USD\") = 1\nIf dict.Exists(\"RUB\") Then MsgBox dict(\"RUB\")",tip:"dict.Keys — массив ключей, dict.Items — массив значений. Идеально для удаления дубликатов."},
{l:3,title:"FileSystemObject",subtitle:"Работа с файлами",body:"FSO — объект для работы с файловой системой: создание, копирование, удаление файлов и папок, чтение текстовых файлов.",example:"Dim fso As Object\nSet fso = CreateObject(\"Scripting.FileSystemObject\")\nIf fso.FileExists(\"C:\\data.csv\") Then\n  fso.CopyFile \"C:\\data.csv\", \"D:\\backup\\\"\nEnd If",tip:"Dir() — встроенная альтернатива для простых задач: If Dir(path) <> \"\" Then — файл существует."},
{l:3,title:"UserForm",subtitle:"Пользовательские формы",body:"Визуальный конструктор диалоговых окон с текстовыми полями, кнопками, списками. Insert → UserForm в редакторе VBA.",example:"' В модуле:\nUserForm1.Show\n' В коде формы:\nPrivate Sub btnOK_Click()\n  Range(\"A1\").Value = txtName.Text\n  Me.Hide\nEnd Sub",tip:"Me.Hide вместо Unload Me сохраняет данные формы. Unload Me освобождает память."},
{l:3,title:"ADO — подключение к БД",subtitle:"Базы данных",body:"ActiveX Data Objects позволяет выполнять SQL-запросы к Access, SQL Server, Oracle прямо из VBA.",example:"Dim cn As Object\nSet cn = CreateObject(\"ADODB.Connection\")\ncn.Open \"Provider=SQLOLEDB;Server=srv;Database=db;...\"\nDim rs As Object\nSet rs = cn.Execute(\"SELECT * FROM Clients\")\nSheet1.Range(\"A2\").CopyFromRecordset rs",tip:"Всегда закрывайте соединение: cn.Close. Используйте параметризованные запросы против SQL-инъекций."},
{l:3,title:"Class Module",subtitle:"ООП в VBA",body:"Классы позволяют создавать собственные объекты с свойствами и методами. Инкапсулируют логику и данные.",example:"' В модуле класса CClient:\nPublic Name As String\nPublic INN As String\nPublic Function GetInfo() As String\n  GetInfo = Name & \" (\" & INN & \")\"\nEnd Function",tip:"Property Get/Let/Set — для контролируемого доступа к свойствам (геттеры/сеттеры)."},
{l:3,title:"RegExp",subtitle:"Регулярные выражения",body:"VBScript.RegExp для поиска и валидации по шаблонам. Незаменим для парсинга текста, проверки форматов.",example:"Dim re As Object\nSet re = CreateObject(\"VBScript.RegExp\")\nre.Pattern = \"\\d{10}\" ' 10 цифр\nre.Global = True\nIf re.Test(\"ИНН: 7712345678\") Then MsgBox \"ИНН найден\"",tip:"Set matches = re.Execute(text) — коллекция всех совпадений."},
{l:3,title:"Коллекция vs Массив",subtitle:"Структуры данных",body:"Collection — динамическая, с ключами, For Each. Массив — быстрый, типизированный, по индексу. Dictionary — гибрид с Exists.",example:"Dim col As New Collection\ncol.Add \"Элемент1\", \"key1\"\ncol.Add \"Элемент2\", \"key2\"\n' Доступ: col(\"key1\") или col(1)",tip:"Dictionary > Collection для поиска по ключу. Array > оба для числовых вычислений."},
{l:3,title:"Timer и DoEvents",subtitle:"Производительность",body:"Timer возвращает секунды для замера скорости. DoEvents позволяет Excel обрабатывать события во время долгих макросов.",example:"Dim t As Double: t = Timer\n' ... длинный код ...\nDebug.Print \"Время: \" & Timer - t & \" сек\"",tip:"DoEvents в цикле позволяет нажать кнопку «Стоп» или увидеть прогресс на StatusBar."},
{l:3,title:"Ribbon XML (CustomUI)",subtitle:"Настройка интерфейса",body:"XML-разметка для создания собственных вкладок, кнопок и групп на ленте Excel. Хранится в файле .xlam.",example:"<customUI>\n <ribbon>\n  <tab id=\"myTab\" label=\"Мои инструменты\">\n   <group id=\"g1\" label=\"Отчёты\">\n    <button id=\"btn1\" label=\"Создать\" onAction=\"RunReport\"/>\n   </group>\n  </tab>\n </ribbon>\n</customUI>",tip:"CustomUI Editor — бесплатная утилита для редактирования Ribbon XML."},
{l:3,title:"Application.StatusBar",subtitle:"Обратная связь",body:"Показывает прогресс выполнения макроса в строке состояния Excel. Лучше чем MsgBox для длинных операций.",example:"For i = 1 To lastRow\n  Application.StatusBar = \"Обработка: \" & i & \" / \" & lastRow\n  ' ... код ...\nNext i\nApplication.StatusBar = False ' сброс",tip:"Обновляйте StatusBar не каждую итерацию, а каждые 100 — иначе замедлит работу."},

// Level 4
{l:4,title:"Класс-обёртка для API",subtitle:"HTTP запросы",body:"WinHttp или XMLHTTP позволяют вызывать REST API из VBA — получать курсы валют, отправлять данные в системы.",example:"Dim http As Object\nSet http = CreateObject(\"MSXML2.XMLHTTP\")\nhttp.Open \"GET\", \"https://api.example.com/rates\", False\nhttp.send\nDim json As String: json = http.responseText",tip:"Для парсинга JSON используйте библиотеку VBA-JSON (JsonConverter). Добавьте через References."},
{l:4,title:"Многопоточность через VBScript",subtitle:"Параллелизм",body:"VBA однопоточный, но можно запустить параллельные VBScript-процессы через Shell для тяжёлых задач.",example:"Shell \"wscript.exe \"\"C:\\script.vbs\"\"\"  ' Запуск параллельного процесса\n' Или через Windows Task Scheduler для фоновых задач",tip:"Альтернатива: разбейте данные на части и обработайте в отдельных книгах через Application.Run."},
{l:4,title:"COM Add-In на VBA",subtitle:"Надстройки",body:"Файл .xlam — надстройка Excel. Код доступен из любой книги. Распространяйте инструменты через сетевую папку.",example:"' Сохраните как .xlam\n' Файл → Параметры → Надстройки → Обзор → выберите .xlam\n' Функции и макросы доступны глобально",tip:"Application.AddIns для программного управления надстройками. Workbook_AddinInstall для инициализации."},
{l:4,title:"Рефакторинг: Модульная архитектура",subtitle:"Архитектура",body:"Разделяйте код: модуль UI (формы, сообщения), модуль Logic (бизнес-логика), модуль Data (чтение/запись), модуль Utils (утилиты).",example:"' modData:\nFunction GetSalesData() As Variant ... End Function\n' modLogic:\nFunction CalcMargin(data As Variant) As Double ... End Function\n' modUI:\nSub ShowReport() ... End Sub",tip:"Каждый модуль должен быть тестируемым отдельно. Минимизируйте зависимости между модулями."},
{l:4,title:"Late vs Early Binding",subtitle:"COM объекты",body:"Early binding (через References) — быстрее, с IntelliSense. Late binding (CreateObject) — без зависимостей, переносимо.",example:"' Early binding (нужна ссылка):\nDim dict As Scripting.Dictionary\n' Late binding (универсально):\nDim dict As Object\nSet dict = CreateObject(\"Scripting.Dictionary\")",tip:"Разрабатывайте с Early binding (для IntelliSense), распространяйте с Late binding (для совместимости)."},
{l:4,title:"Windows API вызовы",subtitle:"Системный уровень",body:"Declare Function позволяет вызывать функции Windows API из VBA — таймеры, файловые диалоги, буфер обмена.",example:"#If VBA7 Then\n  Declare PtrSafe Function GetTickCount Lib \"kernel32\" () As Long\n#Else\n  Declare Function GetTickCount Lib \"kernel32\" () As Long\n#End If",tip:"VBA7 / Win64 — условная компиляция для совместимости 32/64-бит."},
{l:4,title:"Custom Events",subtitle:"Событийная архитектура",body:"Классы могут объявлять и вызывать собственные события через RaiseEvent. Подписчики реагируют через WithEvents.",example:"' Класс CProgress:\nPublic Event ProgressChanged(pct As Long)\nSub Update(pct As Long)\n  RaiseEvent ProgressChanged(pct)\nEnd Sub\n' Модуль формы:\nDim WithEvents prog As CProgress",tip:"Позволяет создать слабую связность между модулями — Observer pattern в VBA."},
{l:4,title:"Защита и обфускация кода",subtitle:"Безопасность",body:"VBA-проект можно защитить паролем (Tools → VBAProject Properties → Protection). Но это слабая защита.",example:"' Для COM Add-In: компилируйте в .dll\n' Для .xlam: пароль + цифровая подпись\nThisWorkbook.VBProject.Protection ' проверка состояния",tip:"Серьёзная защита — COM Add-In на C# или Unviewable+ (сторонний инструмент)."},
{l:4,title:"Оптимизация: массивная запись",subtitle:"Производительность",body:"Запись через Value2 массива в 100x быстрее поячеечной. Для форматирования — один вызов на весь диапазон.",example:"' Медленно (10 сек на 100K строк):\nFor i = 1 To 100000: Cells(i,1) = i: Next\n' Быстро (0.1 сек):\nDim a(1 To 100000, 1 To 1) As Variant\nFor i = 1 To 100000: a(i,1) = i: Next\nRange(\"A1:A100000\").Value2 = a",tip:".Value2 быстрее .Value — не конвертирует Currency и Date."},
{l:4,title:"Treeview и ListView",subtitle:"Сложные формы",body:"MSComctlLib содержит TreeView, ListView, ProgressBar, Toolbar для профессиональных UserForm с деревьями и списками.",example:"' UserForm → Toolbox → правый клик → Additional Controls\n' Отметьте Microsoft Windows Common Controls 6.0\nTreeView1.Nodes.Add , , \"root\", \"Категории\"\nTreeView1.Nodes.Add \"root\", tvwChild, \"ch1\", \"Подкатегория\"",tip:"Эти контролы 32-битные — в 64-bit Office используйте ListView из MSComctlLib_64."},

// Level 5
{l:5,title:"VSTO vs VBA vs Office.js",subtitle:"Архитектурное решение",body:"VBA — быстрый прототип. VSTO (C#) — корпоративный уровень с .NET. Office.js — кроссплатформенный (Web/Desktop/Mobile).",example:"VBA: .xlam, мгновенная разработка\nVSTO: .dll, NuGet, async/await, LINQ\nOffice.js: manifest.xml + HTML/JS, работает в браузере",tip:"Для банков: VSTO для внутренних инструментов (с сертификатом), Office.js для будущих проектов."},
{l:5,title:"Паттерн Repository в VBA",subtitle:"Архитектурные паттерны",body:"Абстрагируйте доступ к данным через класс-репозиторий. Источник (Excel/SQL/API) можно менять не трогая логику.",example:"' IRepository (интерфейс):\nFunction GetAll() As Collection\nSub Save(item As CClient)\n' clsExcelRepo (реализация):\nFunction GetAll() As Collection\n  ' чтение из листа\nEnd Function",tip:"Позволяет тестировать бизнес-логику с mock-данными без реального Excel."},
{l:5,title:"Native Messaging (Chrome↔VBA)",subtitle:"Интеграция",body:"Chrome Extension общается с десктопным .exe через Native Messaging. .exe может вызывать VBA через COM Automation.",example:"' C# host (stdin/stdout):\nvar excel = new Application();\nexcel.Run(\"MyMacro\", param);\n' Chrome extension → native host → Excel VBA",tip:"Именно так работает iBank Досье — Chrome → C# Agent → файловая система."},
{l:5,title:"Compile-time проверки",subtitle:"Качество кода",body:"Option Explicit + MZ-Tools (анализатор) + Rubberduck (рефакторинг) превращают VBA в управляемую среду разработки.",example:"Option Explicit  ' обязательное объявление переменных\nOption Compare Text  ' регистронезависимое сравнение\nOption Base 0  ' массивы с нуля",tip:"Rubberduck VBA — open-source надстройка: Code Inspections, Unit Tests, Refactoring."},
{l:5,title:"Асинхронный паттерн",subtitle:"Архитектура",body:"VBA синхронный, но можно имитировать асинхронность через Application.OnTime и флаги состояния.",example:"' Запуск:\nApplication.OnTime Now + TimeValue(\"00:00:01\"), \"CheckStatus\"\n' Callback:\nSub CheckStatus()\n  If Not taskDone Then\n    Application.OnTime Now + TimeValue(\"00:00:01\"), \"CheckStatus\"\n  Else\n    ProcessResults\n  End If\nEnd Sub",tip:"Используйте для polling внешних систем, мониторинга папок, периодических обновлений."},
{l:5,title:"Unit Testing в VBA",subtitle:"Тестирование",body:"Rubberduck или самописный фреймворк для автоматических тестов. Каждая функция должна иметь тест.",example:"' Тестовый модуль:\nSub TestCalcMargin()\n  Dim result As Double\n  result = CalcMargin(1000, 300)\n  Debug.Assert Abs(result - 0.7) < 0.001\n  Debug.Print \"TestCalcMargin: PASSED\"\nEnd Sub",tip:"Debug.Assert останавливает выполнение при False — примитивный но эффективный Assert."},
{l:5,title:"Интеграция с Power Automate",subtitle:"Облачная автоматизация",body:"Office Scripts вызываются из Power Automate. VBA макросы можно обернуть в Office Script для облачного запуска.",example:"// Office Script (TypeScript):\nfunction main(workbook: ExcelScript.Workbook) {\n  let sheet = workbook.getWorksheet(\"Data\");\n  // ... логика из VBA, переписанная на TS\n}\n// Power Automate → Run Script → этот скрипт",tip:"Миграция VBA → Office Scripts: один модуль за раз, сохраняя ту же бизнес-логику."},
{l:5,title:"Оптимизация: профилирование",subtitle:"Производительность",body:"Создайте класс-профайлер для измерения времени каждого этапа макроса. Оптимизируйте самые медленные участки.",example:"' Class CProfiler:\nPrivate startTime As Double\nSub Start(): startTime = Timer: End Sub\nFunction Elapsed() As Double: Elapsed = Timer - startTime: End Function\n' Использование:\nDim p As New CProfiler\np.Start\n' ... код ...\nDebug.Print \"ETL: \" & p.Elapsed & \"s\"",tip:"90% времени обычно в 10% кода — найдите узкое место перед оптимизацией."},
{l:5,title:"Git для VBA (Rubberduck Export)",subtitle:"Версионирование",body:"Экспортируйте модули VBA в .bas/.cls/.frm файлы и храните в Git. Rubberduck делает это автоматически.",example:"' Rubberduck: Code Explorer → правый клик → Export\n' Структура репозитория:\n/src/modules/modData.bas\n/src/classes/CClient.cls\n/src/forms/frmMain.frm\n/src/forms/frmMain.frx",tip:"CI/CD: PowerShell скрипт импортирует .bas в .xlam и публикует в сетевую папку."},
{l:5,title:"COM-совместимый .NET плагин",subtitle:"Продвинутая интеграция",body:"C# класс с ComVisible(true) доступен из VBA через References. Полная мощь .NET (HTTP, JSON, async) с вызовом из VBA.",example:"[ComVisible(true)]\npublic class BankHelper {\n  public string FetchRate(string currency) {\n    // async HTTP, JSON parsing, caching\n    return rate.ToString();\n  }\n}\n' VBA: Dim h As New BankHelper\n' MsgBox h.FetchRate(\"USD\")",tip:"Регистрация: regasm /codebase MyLib.dll. Для 64-bit Office — компилируйте под x64."},
],

// ═══════════════════════════════════════════
// ADD-IN
// ═══════════════════════════════════════════
addin: [
{l:1,title:"Power Query",subtitle:"Встроенная надстройка",body:"ETL-инструмент для импорта и трансформации данных. Встроен в Excel 2016+. Данные → Получить данные.",example:"Из файла, из папки, из базы данных, из веб — всё через один интерфейс",tip:"Запросы обновляются одной кнопкой или по расписанию."},
{l:1,title:"Power Pivot",subtitle:"Моделирование данных",body:"Аналитический движок для миллионов строк. Связывает таблицы, вычисляет меры на DAX. Встроен в Excel Professional Plus.",example:"Power Pivot → Manage → добавьте таблицы → создайте связи",tip:"Включите через Файл → Параметры → Надстройки → COM-надстройки."},
{l:1,title:"Solver / Поиск решения",subtitle:"Оптимизация",body:"Находит оптимальные значения для ячейки, изменяя другие при заданных ограничениях. Линейное и нелинейное программирование.",example:"Максимизировать прибыль, изменяя цены, при условии: бюджет ≤ 1M, загрузка ≤ 100%",tip:"Данные → Поиск решения. Если нет — включите через Параметры → Надстройки."},
{l:1,title:"Analysis ToolPak",subtitle:"Статистический анализ",body:"Набор статистических инструментов: гистограмма, корреляция, регрессия, t-тест, описательная статистика.",example:"Данные → Анализ данных → Описательная статистика → выберите диапазон",tip:"Включить: Файл → Параметры → Надстройки → Пакет анализа."},
{l:1,title:"Что такое Add-In?",subtitle:"Концепция",body:"Надстройка расширяет функциональность Excel. Бывают: COM (.dll), XLL (.xll), XLAM (.xlam), Office Web Add-in (manifest+JS).",example:"XLAM — макросы VBA в отдельном файле\nCOM — C#/C++ плагин\nWeb Add-in — HTML/JS панель",tip:"Простейший add-in: сохраните .xlsm как .xlam и подключите через Параметры → Надстройки."},
{l:2,title:"XLAM надстройка",subtitle:"VBA Add-In",body:"Файл .xlam — книга с макросами, скрытая от пользователя. Функции и макросы доступны из любой книги Excel.",example:"1. Создайте .xlsm с нужным кодом\n2. Сохраните как .xlam\n3. Файл → Параметры → Надстройки → Обзор\n4. Выберите .xlam → ОК",tip:"Workbook_AddinInstall — событие при подключении. Используйте для создания меню."},
{l:2,title:"Custom Functions (UDF)",subtitle:"Пользовательские функции",body:"Функции в .xlam доступны как обычные формулы. Добавьте описание через Application.MacroOptions.",example:"' В .xlam:\nFunction КУРСЦБ(currency As String) As Double\n  ' ... запрос к API ЦБ ...\nEnd Function\n' В любой книге: =КУРСЦБ(\"USD\")",tip:"Application.MacroOptions Macro:=\"КУРСЦБ\", Description:=\"Курс ЦБ\" — описание в мастере функций."},
{l:2,title:"Ribbon XML",subtitle:"Кастомная лента",body:"XML-файл customUI14.xml внутри .xlam определяет кнопки, вкладки и группы на ленте Excel.",example:"<customUI><ribbon><tabs>\n  <tab id=\"myTab\" label=\"Мои инструменты\">\n    <group id=\"g1\" label=\"Отчёты\">\n      <button id=\"b1\" label=\"Сформировать\" onAction=\"RunReport\"/>\n    </group>\n  </tab>\n</tabs></ribbon></customUI>",tip:"Office RibbonX Editor — бесплатная утилита для встраивания XML в .xlam."},
{l:3,title:"XLL надстройки",subtitle:"Высокая производительность",body:"XLL — DLL для Excel на C/C++. Функции вычисляются в 10-100 раз быстрее VBA. Для тяжёлых расчётов.",example:"// C API:\nLPXLOPER12 WINAPI MyFunc(LPXLOPER12 x) {\n  // быстрые вычисления\n  return result;\n}",tip:"Excel-DNA — фреймворк для создания XLL на C#. Комбинирует скорость XLL с удобством .NET."},
{l:3,title:"Office Web Add-In",subtitle:"Современные надстройки",body:"HTML/JS надстройка с манифестом XML. Работает в Excel Desktop, Online, iPad. Единый код для всех платформ.",example:"manifest.xml → определяет кнопки и панели\nindex.html → UI на HTML/CSS\napp.js → логика через Office.js API\nExcel.run(ctx => { ... })",tip:"Yeoman generator: yo office — шаблон проекта. Публикация через AppSource или sideloading."},
{l:3,title:"VSTO Add-In (C#)",subtitle:"Корпоративный уровень",body:"Visual Studio Tools for Office — полноценный .NET add-in. Async, LINQ, NuGet, WPF — вся мощь .NET в Excel.",example:"public class ThisAddIn {\n  void ThisAddIn_Startup(object s, EventArgs e) {\n    Globals.Ribbons.MyRibbon.Show();\n  }\n}",tip:"Требует цифровой подписи для корпоративного развёртывания. ClickOnce для обновлений."},
{l:3,title:"Task Pane",subtitle:"Боковая панель",body:"Панель справа от листа — основной UI для Web Add-In и VSTO. HTML-контент в Office Web, WPF/WinForms в VSTO.",example:"<!-- taskpane.html -->\n<div id=\"app\">\n  <input id=\"search\" placeholder=\"Поиск клиента...\">\n  <button onclick=\"findClient()\">Найти</button>\n  <div id=\"results\"></div>\n</div>",tip:"Task Pane сохраняет состояние между переключениями листов. Используйте для dashboard-подобного UI."},
{l:4,title:"Excel-DNA",subtitle:".NET для XLL",body:"Open-source библиотека для создания XLL-надстроек на C#/F#. Производительность C API + удобство .NET.",example:"[ExcelFunction(Description=\"Курс валюты ЦБ РФ\")]\npublic static double GetCBRRate(string currency) {\n  return CbrService.GetRate(currency);\n}",tip:"Поддерживает async функции, IntelliSense, Ribbon, COM-сервер. Идеально для банковских расчётов."},
{l:4,title:"ScriptLab",subtitle:"Прототипирование",body:"Microsoft Script Lab — надстройка для быстрого прототипирования Office.js кода прямо в Excel. TypeScript + HTML.",example:"Вставка → Office Add-Ins → Script Lab\nОткройте редактор → пишите TypeScript + HTML\nРезультат виден мгновенно в Task Pane",tip:"Готовые сниппеты для всех API — лучший способ изучить Office.js."},
{l:4,title:"Shared Runtime",subtitle:"Архитектура Web Add-In",body:"Единый JavaScript runtime для Task Pane, Custom Functions и Ribbon Commands. Общее состояние между компонентами.",example:"// manifest.xml:\n<Runtimes><Runtime resid=\"Shared.Url\" lifetime=\"long\"/></Runtimes>\n// Все компоненты разделяют один глобальный объект",tip:"Позволяет Ribbon-кнопке обращаться к данным Task Pane без повторной загрузки."},
{l:4,title:"Centralized Deployment",subtitle:"Развёртывание",body:"Microsoft 365 Admin Center позволяет развернуть Web Add-In для всей организации. Пользователи получают его автоматически.",example:"admin.microsoft.com → Settings → Integrated Apps\n→ Upload custom app → .xml manifest\n→ Assign to users/groups",tip:"Для VSTO: Group Policy + сетевая папка. Для XLAM: скрипт копирования в %AppData%\\Microsoft\\AddIns."},
{l:5,title:"Office.js Custom Functions",subtitle:"Streaming функции",body:"Custom Functions в Office.js поддерживают streaming — функция обновляется в реальном времени (курсы, цены).",example:"/**\n * @customfunction\n * @streaming\n */\nfunction stockPrice(ticker, invocation) {\n  const interval = setInterval(() => {\n    invocation.setResult(getPrice(ticker));\n  }, 1000);\n  invocation.onCanceled = () => clearInterval(interval);\n}",tip:"В ячейке: =STOCKPRICE(\"AAPL\") — обновляется каждую секунду без пересчёта листа."},
{l:5,title:"COM Shim для безопасности",subtitle:"Изоляция",body:"COM Shim загружает add-in в отдельный AppDomain. Краш надстройки не роняет Excel. Обязательно для production.",example:"// COM Shim Wizard создаёт обёртку\n// Add-in загружается в изолированный домен\n// Отлавливает все исключения",tip:"Без shim один баг в add-in может убить весь Excel. В банковской среде это критично."},
{l:5,title:"Архитектура банковского Add-In",subtitle:"Системный дизайн",body:"Многослойная архитектура: UI (Ribbon/TaskPane) → Service Layer → Cache → API Gateway → Backend (iBank, АБС, ЦБ).",example:"[Ribbon] → btnGetRate_Click\n  → [RateService].GetRate(\"USD\")\n    → [Cache].TryGet → hit? return\n    → [ApiClient].FetchFromCBR()\n    → [Cache].Set(rate, ttl=1h)\n  → [Excel].WriteToCell(rate)",tip:"Кэширование критично: один запрос к API ЦБ вместо 1000 при пересчёте листа."},
{l:5,title:"CI/CD для Office Add-In",subtitle:"DevOps",body:"GitHub Actions собирает, тестирует и публикует add-in. Web Add-In деплоится на Azure/CDN. VSTO — через ClickOnce.",example:"# .github/workflows/deploy.yml\non: push\njobs:\n  build:\n    - npm install && npm run build\n    - az storage blob upload-batch \\\n        --source dist --destination \\$web",tip:"Feature flags позволяют включать новые функции постепенно для групп пользователей."},
],

// ═══════════════════════════════════════════
// GERMAN
// ═══════════════════════════════════════════
german: [
{l:1,title:"der / die / das",subtitle:"Артикли",body:"В немецком три рода: мужской (der), женский (die), средний (das). Род нужно учить вместе со словом — он часто непредсказуем.",example:"der Tisch (стол) — м.р.\ndie Lampe (лампа) — ж.р.\ndas Buch (книга) — ср.р.",tip:"Множественное число всегда die: die Bücher, die Tische, die Lampen."},
{l:1,title:"Guten Tag!",subtitle:"Приветствия",body:"Основные приветствия: Guten Morgen (доброе утро), Guten Tag (добрый день), Guten Abend (добрый вечер), Tschüss (пока).",example:"— Guten Tag! Wie geht es Ihnen?\n— Danke, gut! Und Ihnen?",tip:"Hallo — универсальное неформальное. Auf Wiedersehen — формальное «до свидания»."},
{l:1,title:"die Zahlen (числа)",subtitle:"Числительные",body:"1-10: eins, zwei, drei, vier, fünf, sechs, sieben, acht, neun, zehn. С 13 — как в русском: dreizehn (13), vierzehn (14).",example:"11 = elf, 12 = zwölf\n20 = zwanzig, 21 = einundzwanzig (один-и-двадцать)\n100 = hundert, 1000 = tausend",tip:"Числа 21-99 читаются «наоборот»: 45 = fünfundvierzig (пять-и-сорок)."},
{l:1,title:"sein (быть)",subtitle:"Базовые глаголы",body:"Самый важный глагол. Спрягается нерегулярно: ich bin, du bist, er/sie/es ist, wir sind, ihr seid, sie/Sie sind.",example:"Ich bin Student. — Я студент.\nSie ist Managerin. — Она менеджер.\nWir sind aus Russland. — Мы из России.",tip:"Sie (с заглавной) = Вы (вежливая форма). sie (строчная) = она/они."},
{l:1,title:"haben (иметь)",subtitle:"Базовые глаголы",body:"Второй по важности глагол: ich habe, du hast, er hat, wir haben, ihr habt, sie haben. Используется для Perfekt.",example:"Ich habe eine Frage. — У меня вопрос.\nEr hat zwei Kinder. — У него двое детей.\nHast du Zeit? — У тебя есть время?",tip:"Haben + Partizip II = прошедшее время: Ich habe gemacht (Я сделал)."},
{l:1,title:"die Woche (неделя)",subtitle:"Время",body:"Montag, Dienstag, Mittwoch, Donnerstag, Freitag, Samstag, Sonntag. Все мужского рода (der Montag).",example:"Am Montag habe ich ein Meeting.\nВ понедельник у меня встреча.\nAm Wochenende — на выходных",tip:"«Am» + день недели: am Dienstag (во вторник). Месяцы: im Januar, im Februar..."},
{l:1,title:"Wie viel kostet das?",subtitle:"В магазине",body:"Сколько это стоит? Базовая фраза для покупок. Ответ: Das kostet ... Euro/Cent.",example:"— Wie viel kostet der Kaffee?\n— Der Kaffee kostet drei Euro fünfzig.\n— Ich nehme ihn. (Я возьму его.)",tip:"Ich möchte... (Я хотел бы...) — вежливая форма заказа."},
{l:1,title:"Wo? Wohin? Woher?",subtitle:"Вопросительные слова",body:"Wo = где, Wohin = куда, Woher = откуда. Определяют падеж: Wo → Dativ, Wohin → Akkusativ.",example:"Wo wohnst du? — Где ты живёшь?\nWohin gehst du? — Куда ты идёшь?\nWoher kommst du? — Откуда ты?",tip:"Wo bist du? (Где ты?) vs Wohin gehst du? (Куда идёшь?) — ключевое различие."},
{l:2,title:"Akkusativ",subtitle:"Винительный падеж",body:"Отвечает на Wen? Was? (Кого? Что?). Меняется только мужской артикль: der→den, ein→einen. Остальные без изменений.",example:"Ich sehe den Mann. (der→den)\nIch kaufe einen Computer. (ein→einen)\nIch trinke die Milch. (без изменений)",tip:"Предлоги Akkusativ: durch, für, gegen, ohne, um — всегда Akkusativ после них."},
{l:2,title:"Dativ",subtitle:"Дательный падеж",body:"Отвечает на Wem? (Кому?). der→dem, die→der, das→dem, die(мн.)→den(+n). Существительные мн.ч. добавляют -n.",example:"Ich gebe dem Mann das Buch.\nSie hilft der Frau.\nMit den Kindern (с детьми)",tip:"Предлоги Dativ: aus, bei, mit, nach, seit, von, zu — всегда Dativ."},
{l:2,title:"Trennbare Verben",subtitle:"Отделяемые приставки",body:"Приставки an-, auf-, ein-, mit-, zu- и др. отделяются в Present и ставятся в конец предложения.",example:"aufstehen → Ich stehe um 7 Uhr auf.\nanrufen → Ruf mich bitte an!\neinkaufen → Wir kaufen im Supermarkt ein.",tip:"В Perfekt: приставка + ge + корень: aufgestanden, angerufen, eingekauft."},
{l:2,title:"Modalverben",subtitle:"Модальные глаголы",body:"können (мочь), müssen (должен), wollen (хотеть), sollen (следует), dürfen (разрешено), mögen (нравиться).",example:"Ich kann Deutsch sprechen.\nDu musst das Formular ausfüllen.\nSie dürfen hier nicht rauchen.",tip:"Модальный глагол спрягается, основной идёт в конец в Infinitiv: Ich will nach Hause gehen."},
{l:2,title:"Perfekt",subtitle:"Прошедшее время",body:"Основное разговорное прошедшее время. haben/sein + Partizip II. Partizip II: ge- + корень + -t (слабые) или -en (сильные).",example:"Ich habe gemacht (я сделал) — machen\nIch bin gegangen (я ушёл) — gehen\nEr hat angerufen (он позвонил) — anrufen",tip:"С sein: глаголы движения (gehen, fahren, fliegen) и изменения состояния (werden, sterben)."},
{l:2,title:"Konjunktionen",subtitle:"Союзы",body:"Порядок слов зависит от типа союза. und, aber, oder — не меняют. weil, dass, wenn — глагол в конец.",example:"Ich lerne, weil ich den Test bestehen will.\n(Я учусь, потому что хочу сдать тест.)\nIch denke, dass er recht hat.",tip:"После weil, dass, wenn, ob, als, obwohl — глагол всегда в КОНЦЕ предложения."},
{l:3,title:"Konjunktiv II",subtitle:"Сослагательное наклонение",body:"Для вежливых просьб, нереальных условий, желаний. Основа: würde + Infinitiv или специальные формы (hätte, wäre, könnte).",example:"Ich würde gern einen Kaffee bestellen.\nWenn ich reich wäre, würde ich reisen.\nKönnten Sie mir bitte helfen?",tip:"hätte (имел бы), wäre (был бы), könnte (мог бы) — три самых важных формы."},
{l:3,title:"Relativsätze",subtitle:"Относительные предложения",body:"Определяют существительное через der/die/das (который/ая/ое). Глагол — в конце. Род и число = определяемому слову.",example:"Der Mann, der dort steht, ist mein Chef.\n(Мужчина, который там стоит — мой начальник.)\nDas Buch, das ich lese, ist interessant.",tip:"Падеж относительного местоимения зависит от его роли в придаточном, не в главном предложении."},
{l:3,title:"Passiv",subtitle:"Страдательный залог",body:"werden + Partizip II. Используется чаще чем в русском, особенно в деловом и официальном языке.",example:"Das Dokument wird unterschrieben.\n(Документ подписывается.)\nDie Rechnung wurde bezahlt.\n(Счёт был оплачен.)",tip:"von + Dativ для указания деятеля: Das Buch wird von dem Autor geschrieben."},
{l:3,title:"Geschäftssprache",subtitle:"Деловой немецкий",body:"Ключевые фразы: Sehr geehrte Damen und Herren (обращение в письме), mit freundlichen Grüßen (с уважением).",example:"Bezüglich Ihrer Anfrage... — По поводу Вашего запроса...\nAnbei finden Sie... — В приложении Вы найдёте...\nWir bitten um baldige Rückmeldung.",tip:"В деловом немецком используйте Sie-форму и Konjunktiv II для вежливости."},
{l:4,title:"Nominalstil",subtitle:"Канцелярский стиль",body:"В деловом немецком предпочитают существительные вместо глаголов: Durchführung (проведение) вместо durchführen (проводить).",example:"die Überprüfung (проверка) ← überprüfen\ndie Bearbeitung (обработка) ← bearbeiten\nzur Kenntnisnahme — для сведения\nin Bezug auf + Akk. — в отношении",tip:"-ung, -tion, -heit, -keit — типичные суффиксы отглагольных существительных."},
{l:4,title:"Funktionsverbgefüge",subtitle:"Устойчивые сочетания",body:"Глагол + существительное вместо простого глагола. Типичны для официального стиля.",example:"eine Entscheidung treffen = entscheiden (принять решение)\nin Betracht ziehen = berücksichtigen (принять во внимание)\nzur Verfügung stellen = bereitstellen (предоставить)",tip:"Знание этих конструкций — маркер продвинутого немецкого в деловой среде."},
{l:4,title:"Indirekte Rede",subtitle:"Косвенная речь",body:"Konjunktiv I используется для передачи чужих слов, особенно в СМИ и официальных текстах. er sei, er habe, er könne.",example:"Direct: Er sagt: «Ich bin krank.»\nIndirect: Er sagt, er sei krank.\nDer Minister erklärte, die Wirtschaft wachse.",tip:"Если Konjunktiv I совпадает с Indikativ — используйте Konjunktiv II: sie hätten (не: sie haben)."},
{l:5,title:"Fachsprache: Bankwesen",subtitle:"Банковская терминология",body:"Профессиональная лексика банковского сектора на немецком — для работы с немецкоязычными партнёрами и документами.",example:"die Überweisung — перевод\ndas Girokonto — текущий счёт\ndie Zinsen — проценты\nder Kredit — кредит\ndie Sicherheit — обеспечение/залог",tip:"der Kontoauszug (выписка), die Gutschrift (зачисление), die Belastung (списание)."},
{l:5,title:"Partizipialattribut",subtitle:"Причастные обороты",body:"Развёрнутые причастные определения перед существительным — визитная карточка сложного немецкого текста.",example:"die in der letzten Sitzung beschlossenen Maßnahmen\n= меры, принятые на последнем заседании\n\nder seit Jahren anhaltende Trend\n= тенденция, сохраняющаяся на протяжении лет",tip:"Читайте справа налево: найдите существительное, затем разверните определение."},
],

// ═══════════════════════════════════════════
// ENGLISH
// ═══════════════════════════════════════════
english: [
{l:1,title:"Present Simple vs Continuous",subtitle:"Tenses",body:"Simple: привычки и факты (I work). Continuous: действие прямо сейчас (I am working). Ключевое различие для русскоговорящих.",example:"I work at a bank. (Я работаю в банке — факт)\nI am working on a report now. (Сейчас работаю над отчётом)",tip:"Stative verbs (know, want, like, need) не используются в Continuous."},
{l:1,title:"Articles: a / an / the",subtitle:"Артикли",body:"a/an — неопределённый (один из многих). the — определённый (конкретный, известный обоим). Нет артикля — обобщение.",example:"I need a pen. (любая ручка)\nThe pen on your desk. (конкретная)\nPens are useful. (ручки вообще)",tip:"Перед гласным звуком: an hour (h немое), a university (звук /ju/)."},
{l:1,title:"there is / there are",subtitle:"Конструкции",body:"Используется для описания наличия чего-либо. There is — единственное число, There are — множественное.",example:"There is a meeting at 3 PM.\nThere are five reports on the desk.\nIs there a problem? — Есть проблема?",tip:"В разговорной речи: There's вместо There is, но There're используется редко."},
{l:2,title:"Present Perfect",subtitle:"Грамматика времён",body:"have/has + V3. Связь прошлого с настоящим: результат, опыт, незавершённое действие. Маркеры: already, yet, ever, never, since, for.",example:"I have finished the report. (результат)\nHave you ever been to London? (опыт)\nShe has worked here since 2020. (с 2020 до сих пор)",tip:"Since + момент (since Monday). For + период (for 3 years). Типичная ошибка русскоговорящих."},
{l:2,title:"Leverage",subtitle:"Business Vocabulary",body:"Как существительное: рычаг, кредитное плечо. Как глагол: использовать что-то для максимальной выгоды. Ключевое слово в финансах.",example:"We can leverage our expertise. (использовать экспертизу)\nThe deal has high leverage. (высокое кредитное плечо)\nLeveraged buyout = LBO",tip:"Overused в корпоративном жаргоне. Синонимы: utilize, capitalize on, exploit."},
{l:2,title:"Conditional 1 & 2",subtitle:"Условные предложения",body:"Type 1: реальное условие (If + Present → will + V). Type 2: нереальное (If + Past → would + V).",example:"If we close the deal, we will get a bonus. (Type 1 — реально)\nIf I were the CEO, I would change the strategy. (Type 2 — нереально)",tip:"If I were (не was) — стандартная форма для Type 2, даже с I/he/she."},
{l:2,title:"Phrasal Verbs: Business",subtitle:"Фразовые глаголы",body:"Фразовые глаголы критичны для делового английского. Отличие от формальных синонимов — стиль.",example:"bring up = raise (поднять тему)\nput off = postpone (отложить)\ncarry out = implement (выполнить)\nturn down = reject (отклонить)",tip:"В формальных письмах используйте латинские синонимы: carry out → implement."},
{l:3,title:"Reported Speech",subtitle:"Косвенная речь",body:"Сдвиг времён при передаче чужих слов: Present→Past, Past→Past Perfect, will→would.",example:"He said: 'I will send the report.'\n→ He said he would send the report.\nShe told me: 'I have finished.'\n→ She told me she had finished.",tip:"Если информация всё ещё актуальна, сдвиг времени необязателен: He said he is busy."},
{l:3,title:"Subjunctive Mood",subtitle:"Сослагательное наклонение",body:"Используется после suggest, recommend, insist, demand, require. Глагол в базовой форме без -s.",example:"I suggest he attend the meeting. (не attends)\nThe board recommended that she be promoted.\nIt is essential that the report be submitted.",tip:"В британском английском часто заменяют на should: I suggest he should attend."},
{l:3,title:"Collocations: Finance",subtitle:"Устойчивые сочетания",body:"Словосочетания, которые нужно знать целиком. Нельзя заменять отдельные слова — звучит неестественно.",example:"raise capital (привлечь капитал) ≠ lift capital\nclose a deal (закрыть сделку) ≠ shut a deal\nrun the numbers (посчитать) ≠ walk the numbers\nballpark figure (примерная оценка)",tip:"Читайте FT и WSJ — лучший способ впитать правильные collocations."},
{l:4,title:"Hedging Language",subtitle:"Язык осторожных формулировок",body:"Смягчение утверждений для профессионального общения: might, could, tend to, it appears, arguably.",example:"This could potentially impact Q4 results.\nThe data seems to suggest a downward trend.\nIt would appear that costs have been underestimated.",tip:"Чем серьёзнее заявление — тем больше hedging. «Revenue will drop» → «Revenue may potentially decline.»"},
{l:4,title:"Inversion for Emphasis",subtitle:"Инверсия",body:"Вынос наречия в начало с инверсией — формальный стиль, характерный для финансовых отчётов и презентаций.",example:"Not only did revenue increase, but margins expanded too.\nUnder no circumstances should this be disclosed.\nRarely have we seen such market volatility.",tip:"Только с негативными/ограничительными наречиями: never, seldom, rarely, hardly, not only, no sooner."},
{l:5,title:"Nominalisation",subtitle:"Академический/деловой стиль",body:"Превращение глаголов в существительные делает текст формальнее: analyze→analysis, implement→implementation.",example:"Informal: We need to analyze the data before we decide.\nFormal: An analysis of the data is required prior to a decision.\n\nThe implementation of new regulations necessitated a review.",tip:"Номинализация = признак C1-C2 уровня. Но избыток делает текст тяжёлым — балансируйте."},
{l:5,title:"Advanced Connectors",subtitle:"Связующие слова",body:"Продвинутые связки для аналитических текстов и презентаций. Уровень C1-C2.",example:"notwithstanding — несмотря на\ninsofar as — постольку, поскольку\nby virtue of — в силу\nirrespective of — безотносительно\nhaving said that — тем не менее",tip:"Не перегружайте — 1-2 продвинутых коннектора на абзац достаточно."},
],

// ═══════════════════════════════════════════
// JAPANESE
// ═══════════════════════════════════════════
japanese: [
{l:1,title:"ひらがな (Хирагана)",subtitle:"Письменность",body:"Базовая азбука из 46 символов. Используется для японских слов, окончаний, частиц. Первое, что нужно выучить.",example:"あ(a) い(i) う(u) え(e) お(o)\nか(ka) き(ki) く(ku) け(ke) こ(ko)\nさ(sa) し(shi) す(su) せ(se) そ(so)",tip:"Учите по строкам (あ行, か行, さ行...). 2 недели — и вы читаете хирагану свободно."},
{l:1,title:"です / ます",subtitle:"Вежливая речь",body:"Базовый вежливый стиль (丁寧語). です — «есть/является», ます — вежливое окончание глаголов.",example:"わたしは学生です。\nWatashi wa gakusei desu.\nЯ студент.\n\nにほんごをべんきょうします。\nNihongo wo benkyou shimasu.\nЯ изучаю японский.",tip:"Всегда используйте です/ます с незнакомыми людьми и на работе."},
{l:1,title:"Частица は (wa)",subtitle:"Базовые частицы",body:"Тематическая частица — указывает тему предложения. Пишется は (ha), читается wa.",example:"わたしはドニヨルです。\nWatashi wa Doniyor desu.\nЯ — Дониёр.\n\nこれはペンです。\nKore wa pen desu.\nЭто ручка.",tip:"は ≠ が: は — тема (о чём речь), が — подлежащее (кто делает). Тонкая разница!"},
{l:1,title:"カタカナ (Катакана)",subtitle:"Письменность",body:"Вторая азбука для иностранных слов, имён, звукоподражаний. Те же звуки что хирагана, другие символы.",example:"ア(a) イ(i) ウ(u) エ(e) オ(o)\nコンピュータ (kompyuuta) — компьютер\nロシア (Roshia) — Россия\nバンク (banku) — банк",tip:"Много банковских терминов в катакане: クレジット (кредит), デポジット (депозит)."},
{l:2,title:"て-форма (te-form)",subtitle:"Ключевая грамматика",body:"Основа для десятков конструкций: ~ている (длящееся), ~てください (просьба), ~てもいい (разрешение).",example:"食べて (tabete) ← 食べる\n飲んで (nonde) ← 飲む\n行って (itte) ← 行く\n\n食べています — (сейчас) ем\n食べてください — пожалуйста, ешьте",tip:"Правила образования зависят от группы глагола. Запоминайте песенкой: て-song."},
{l:2,title:"Счётные суффиксы",subtitle:"Числительные",body:"В японском предметы считаются с суффиксами по форме: 人(люди), 本(длинные), 枚(плоские), 台(машины).",example:"三人 (san-nin) — 3 человека\n二本 (ni-hon) — 2 бутылки/ручки\n一枚 (ichi-mai) — 1 лист\n五台 (go-dai) — 5 машин",tip:"Универсальный ряд: ひとつ、ふたつ、みっつ... до とお (10) — для любых предметов."},
{l:3,title:"敬語 (Кэйго)",subtitle:"Уровни вежливости",body:"Три уровня: 尊敬語 (почтительный — о действиях других), 謙譲語 (скромный — о своих), 丁寧語 (вежливый — です/ます).",example:"行く → いらっしゃる (尊敬語, о начальнике)\n行く → 参る (謙譲語, о себе)\n行く → 行きます (丁寧語, нейтрально)",tip:"В бизнес-японском кэйго обязательно. Ошибка в уровне = серьёзный faux pas."},
{l:3,title:"ビジネス日本語",subtitle:"Деловой японский",body:"Фразы для делового общения: встречи, переговоры, переписка. Критично для работы с японскими партнёрами.",example:"お世話になっております (osewa ni natte orimasu)\n— стандартное начало делового письма/звонка\n\nご検討のほど、よろしくお願いいたします\n— просим рассмотреть наше предложение",tip:"初めまして — только при ПЕРВОЙ встрече. Потом — お世話になっております."},
{l:4,title:"漢字: 金融 (Финансы)",subtitle:"Кандзи",body:"Ключевые кандзи финансовой сферы для чтения японских документов.",example:"銀行 (ginkou) — банк\n為替 (kawase) — валютный обмен\n株式 (kabushiki) — акции\n利益 (rieki) — прибыль\n投資 (toushi) — инвестиции",tip:"金 (kane/kin) — деньги/золото. Встречается в 銀行, 金融, 金利, 預金."},
{l:5,title:"ビジネスメール",subtitle:"Деловая переписка",body:"Структура японского делового письма: 宛名(адресат) → 挨拶(приветствие) → 本文(суть) → 結び(заключение) → 署名(подпись).",example:"○○株式会社\n△△部 □□様\n\nお世話になっております。\nАИБ銀行の○○です。\n\n...本文...\n\n何卒よろしくお願い申し上げます。",tip:"Длинные формулы вежливости — норма. Краткость воспринимается как грубость."},
],

// ═══════════════════════════════════════════
// INVESTMENT BANKING
// ═══════════════════════════════════════════
ib: [
{l:1,title:"Что такое Investment Banking?",subtitle:"Введение",body:"Инвестиционный банк помогает компаниям привлекать капитал (IPO, облигации) и совершать сделки (M&A). Зарабатывает на комиссиях.",example:"Goldman Sachs консультирует компанию X по покупке компании Y за $5B → комиссия 1% = $50M",tip:"IB ≠ коммерческий банк. IB не принимает вклады и не выдаёт кредиты населению."},
{l:1,title:"M&A (Mergers & Acquisitions)",subtitle:"Слияния и поглощения",body:"Процесс покупки одной компании другой (acquisition) или объединения двух компаний (merger). Основной источник доходов IB.",example:"Facebook купил Instagram за $1B (2012) — это acquisition.\nExxon + Mobil = ExxonMobil (1999) — это merger.",tip:"Buy-side: советуем покупателю. Sell-side: советуем продавцу. Разные стратегии."},
{l:1,title:"IPO (Initial Public Offering)",subtitle:"Первичное размещение",body:"Первая продажа акций компании на бирже. IB выступает андеррайтером — определяет цену, находит инвесторов, управляет процессом.",example:"Компания оценена в $10B → IPO 10% акций → привлекает $1B → комиссия IB ~3-7%",tip:"Bookbuilding — процесс сбора заявок от инвесторов для определения цены IPO."},
{l:1,title:"Revenue vs Profit",subtitle:"Финансовые основы",body:"Revenue (выручка) — все деньги от продаж. Profit (прибыль) — что остаётся после расходов. Компания может расти по выручке, но терять прибыль.",example:"Revenue: $100M\n- COGS: $60M\n= Gross Profit: $40M\n- OpEx: $25M\n= EBITDA: $15M",tip:"Top line = Revenue (верх P&L). Bottom line = Net Income (низ P&L)."},
{l:2,title:"DCF (Discounted Cash Flow)",subtitle:"Оценка компаний",body:"Метод оценки: прогнозируем будущие денежные потоки, дисконтируем по ставке WACC, добавляем Terminal Value.",example:"Год 1: FCF $100M / (1+10%)¹ = $90.9M\nГод 2: FCF $110M / (1+10%)² = $90.9M\n...\n+ Terminal Value\n= Enterprise Value",tip:"Terminal Value = 60-80% оценки. Два метода: Gordon Growth и Exit Multiple."},
{l:2,title:"EBITDA",subtitle:"Ключевая метрика",body:"Earnings Before Interest, Taxes, Depreciation & Amortization. Прибыль до вычета процентов, налогов и амортизации. Proxy для операционного денежного потока.",example:"Revenue $500M - COGS $300M - SGA $100M = EBITDA $100M\nEBITDA margin = 100/500 = 20%",tip:"EBITDA ≠ Cash Flow. Не учитывает CapEx, Working Capital, налоги. Используйте осторожно."},
{l:2,title:"Enterprise Value vs Equity Value",subtitle:"Оценка",body:"EV = стоимость всего бизнеса (для всех инвесторов). Equity = стоимость только для акционеров. EV = Equity + Debt - Cash.",example:"Market Cap: $800M\n+ Debt: $300M\n- Cash: $100M\n= EV: $1,000M",tip:"EV-based мультипликаторы (EV/EBITDA) сравнимы между компаниями с разной структурой капитала."},
{l:2,title:"Comparable Companies",subtitle:"Оценка по аналогам",body:"Оценка на основе мультипликаторов похожих публичных компаний. Выбираем peers, считаем медианный мультипликатор, применяем к нашей компании.",example:"Peer median EV/EBITDA = 8x\nНаша EBITDA = $50M\nПодразумеваемый EV = $400M",tip:"Выбор peers критичен. Критерии: отрасль, размер, рост, маржа, география."},
{l:3,title:"LBO Model",subtitle:"Leveraged Buyout",body:"PE-фонд покупает компанию в основном за заёмные средства. Компания сама выплачивает долг из cash flow. Прибыль = рост equity.",example:"Покупка за $1B: Equity $300M + Debt $700M\nЧерез 5 лет: Debt = $400M, EV = $1.2B\nEquity = $1.2B - $400M = $800M\nReturn = $800M / $300M = 2.7x",tip:"Три рычага доходности LBO: погашение долга, рост EBITDA, расширение мультипликатора."},
{l:3,title:"WACC",subtitle:"Ставка дисконтирования",body:"Weighted Average Cost of Capital — средневзвешенная стоимость капитала. Учитывает стоимость долга (после налогов) и equity.",example:"WACC = E/(D+E) × Ke + D/(D+E) × Kd × (1-T)\nKe = Rf + β × (Rm-Rf) — из CAPM\nПример: 60%×12% + 40%×5%×(1-20%) = 8.8%",tip:"Чем выше риск бизнеса — тем выше WACC — тем ниже DCF-оценка."},
{l:3,title:"Pitchbook",subtitle:"Маркетинговые материалы",body:"Презентация для потенциального клиента. Включает: обзор банка, рыночный контекст, оценку, предлагаемую стратегию.",example:"Структура pitchbook:\n1. Executive Summary\n2. Situation Overview\n3. Valuation Analysis\n4. Transaction Considerations\n5. Credentials & Case Studies",tip:"Pitchbook — не просто слайды, а инструмент продажи. Каждая страница должна вести к mandated."},
{l:3,title:"Due Diligence",subtitle:"Проверка",body:"Всесторонняя проверка компании перед сделкой: финансовая, юридическая, налоговая, коммерческая, IT, HR, ESG.",example:"Financial DD: качество earnings, working capital, CapEx\nLegal DD: контракты, судебные иски, IP\nCommercial DD: рынок, конкуренция, клиенты",tip:"Red flags в DD могут снизить цену или убить сделку. Качество DD = качество решения."},
{l:4,title:"Accretion/Dilution Analysis",subtitle:"M&A Analytics",body:"Анализирует влияние сделки на EPS покупателя. Accretive = EPS растёт. Dilutive = EPS падает. Ключевой тест для M&A.",example:"Покупатель EPS: $2.00\nПосле сделки EPS: $2.15 → Accretive (+7.5%)\nИли EPS: $1.85 → Dilutive (-7.5%)",tip:"Dilutive сделка не обязательно плохая — стратегическая ценность может перевешивать."},
{l:4,title:"Precedent Transactions",subtitle:"Оценка по прецедентам",body:"Оценка на основе мультипликаторов прошлых M&A сделок в отрасли. Включает премию за контроль.",example:"Медианный EV/EBITDA прошлых сделок = 10x\n(vs trading comps = 8x → премия за контроль ~25%)\nНаша EBITDA $50M → EV = $500M",tip:"Precedent transactions обычно выше trading comps из-за control premium (20-40%)."},
{l:4,title:"Fairness Opinion",subtitle:"Корпоративное управление",body:"Независимое заключение банка о справедливости цены сделки. Защищает совет директоров от исков акционеров.",example:"«По нашему мнению, цена $X за акцию является справедливой с финансовой точки зрения для акционеров Компании.»",tip:"Fairness opinion — обязательная практика для публичных M&A в США. Комиссия: $1-5M."},
{l:5,title:"Sum-of-the-Parts (SOTP)",subtitle:"Оценка конгломератов",body:"Оценка каждого подразделения отдельно как standalone бизнеса. Сумма > текущей EV = conglomerate discount.",example:"Дивизион A: $3B (EV/EBITDA 12x)\nДивизион B: $2B (EV/EBITDA 8x)\nSOTP = $5B vs Market Cap $4B\n→ Conglomerate discount 20%",tip:"Активистские инвесторы используют SOTP для обоснования разделения компаний."},
{l:5,title:"Merger Model",subtitle:"Полная модель сделки",body:"Комплексная финансовая модель M&A: purchase price allocation, pro forma P&L, accretion/dilution, synergies, financing structure.",example:"Sources: Cash $200M, New Debt $500M, Stock $300M\nUses: Equity $900M, Fees $50M, Refinancing $50M\nPro Forma: Combined EBITDA + Synergies - Financing Costs",tip:"Synergies — ключевой драйвер. Revenue synergies сложнее реализовать чем cost synergies."},
{l:5,title:"Restructuring",subtitle:"Реструктуризация",body:"Финансовая реструктуризация компании в кризисе. Переговоры с кредиторами, обмен долга на equity, Chapter 11 (США).",example:"Долг $1B, компания стоит $600M\n→ Кредиторы получают equity = $600M\n→ Старые акционеры = $0 (wiped out)\n→ Fulcrum security analysis",tip:"Waterfall analysis определяет кто получает что. Fulcrum security — класс долга, который «ломается»."},
],

// ═══════════════════════════════════════════
// PRIVATE EQUITY
// ═══════════════════════════════════════════
pe: [
{l:1,title:"Что такое Private Equity?",subtitle:"Введение",body:"PE-фонд привлекает деньги инвесторов (LP), покупает компании, улучшает их за 3-7 лет и продаёт с прибылью.",example:"PE-фонд $1B → покупает 5 компаний → улучшает → продаёт → возвращает $2-3B инвесторам",tip:"PE ≠ Venture Capital. PE покупает зрелые компании, VC инвестирует в стартапы."},
{l:1,title:"GP и LP",subtitle:"Структура фонда",body:"GP (General Partner) — управляющая компания, принимает решения. LP (Limited Partners) — инвесторы (пенсионные фонды, endowments).",example:"LP вложили $900M + GP вложил $100M = фонд $1B\nGP получает management fee + carried interest\nLP получают прибыль минус комиссии",tip:"LP несут ограниченную ответственность (limited liability). GP — полную."},
{l:1,title:"Management Fee",subtitle:"Комиссии",body:"Ежегодная комиссия GP за управление фондом. Обычно 1.5-2% от committed capital. Покрывает операционные расходы.",example:"Фонд $1B × 2% = $20M/год management fee\nЗа 10 лет жизни фонда = $200M total fees",tip:"Часто снижается после инвестиционного периода (первые 5 лет) — с committed на invested capital."},
{l:1,title:"Carried Interest (Carry)",subtitle:"Вознаграждение GP",body:"Доля прибыли фонда для GP. Обычно 20% от прибыли после возврата капитала LP и preferred return.",example:"Фонд $500M → exits $1.2B → прибыль $700M\nPreferred return 8% = $200M сначала LP\nОстаток $500M: 80% LP ($400M), 20% GP ($100M)",tip:"Carry — главная мотивация GP. Выплачивается только при успешных выходах."},
{l:2,title:"LBO (Leveraged Buyout)",subtitle:"Основная стратегия PE",body:"Покупка компании с использованием заёмных средств (60-80% цены). Компания сама обслуживает долг из своего cash flow.",example:"Покупка за $500M:\nEquity (PE фонд): $150M (30%)\nDebt (банки): $350M (70%)\nКомпания выплачивает долг из EBITDA",tip:"Хороший LBO-кандидат: стабильный cash flow, низкий CapEx, сильная рыночная позиция."},
{l:2,title:"IRR (Internal Rate of Return)",subtitle:"Метрика доходности",body:"Годовая доходность инвестиции с учётом времени. В PE целевой IRR: 20-25%+. Зависит от MOIC и времени.",example:"Вложили $100M, через 5 лет получили $250M\nMOIC = 2.5x\nIRR ≈ 20%\n\nТе же $250M через 3 года → IRR ≈ 36%",tip:"IRR зависит от времени: быстрый exit c 2x лучше медленного с 3x по IRR."},
{l:2,title:"MOIC (Multiple on Invested Capital)",subtitle:"Метрика доходности",body:"Во сколько раз вырос вложенный капитал. MOIC 2.5x = вернули в 2.5 раза больше чем вложили.",example:"Инвестировали $200M → получили $600M\nMOIC = $600M / $200M = 3.0x\nGross MOIC (до комиссий) vs Net MOIC (после)",tip:"Top-quartile PE фонды: Net MOIC 2.0x+. Медиана ~1.5-1.8x."},
{l:2,title:"Value Creation",subtitle:"Три рычага",body:"PE создаёт стоимость тремя способами: рост EBITDA (операционные улучшения), погашение долга (deleveraging), расширение мультипликатора.",example:"Покупка: 8x EBITDA $50M = EV $400M\nExit: 10x EBITDA $80M = EV $800M\nРост EV = EBITDA рост + multiple expansion",tip:"Операционные улучшения — самый надёжный рычаг. Multiple expansion зависит от рынка."},
{l:3,title:"J-Curve",subtitle:"Динамика фонда",body:"В первые годы IRR отрицательный (комиссии + нереализованные инвестиции). Прибыль приходит при выходах через 3-7 лет.",example:"Год 1-2: IRR = -15% (management fees, no exits)\nГод 3-4: IRR = 0% (первые exits)\nГод 5-7: IRR = 20%+ (bulk of exits)",tip:"LP должны понимать J-curve при планировании ликвидности — capital calls идут в первые годы."},
{l:3,title:"100-Day Plan",subtitle:"Post-Acquisition",body:"План действий на первые 100 дней после покупки компании. Quick wins, стратегические инициативы, новая управленческая команда.",example:"Дни 1-30: Аудит, знакомство с командой\nДни 31-60: Quick wins (costs, pricing)\nДни 61-100: Стратегические инициативы (M&A, expansion)",tip:"Quick wins — критически важны для создания импульса и доверия с менеджментом."},
{l:3,title:"Add-on Acquisition",subtitle:"Buy-and-Build",body:"Покупка меньшей компании для присоединения к портфельной. Стратегия роста + синергии + arbitrage мультипликатора.",example:"Platform: куплена за 10x EBITDA\nAdd-on: куплен за 6x EBITDA\nCombined: оценивается по 10x → мгновенный рост EV",tip:"Multiple arbitrage: покупаешь мелкую дёшево, присоединяешь к крупной, оценка растёт."},
{l:4,title:"Waterfall Distribution",subtitle:"Структура выплат",body:"Порядок распределения прибыли: 1) Return of Capital, 2) Preferred Return (hurdle), 3) Catch-up (GP), 4) Carried Interest.",example:"$100M invested, $200M return:\n1) LP gets $100M back (return of capital)\n2) LP gets 8% preferred = ~$40M\n3) GP catch-up: ~$10M\n4) Remaining $50M: 80/20 split",tip:"European waterfall: по всему фонду. American: по каждой сделке. European лучше защищает LP."},
{l:4,title:"Operational Due Diligence",subtitle:"Глубокий анализ",body:"Помимо финансов, PE анализирует операции: качество менеджмента, IT-системы, процессы, клиентская концентрация, ESG.",example:"Red flags:\n- Один клиент > 20% выручки\n- Ключевой сотрудник без замены\n- Устаревшая IT-инфраструктура\n- Судебные иски > 5% EV",tip:"Operating partners в PE-фонде — бывшие CEO/CFO, которые проводят операционный DD."},
{l:4,title:"Co-Investment",subtitle:"Совместные инвестиции",body:"LP инвестируют напрямую в сделку рядом с фондом, обычно без management fee и carry. Увеличивает exposure.",example:"Сделка $500M:\nФонд: $200M (с комиссиями)\nCo-invest LP: $150M (без комиссий)\nБанковский долг: $150M",tip:"Co-invest — способ для LP снизить blended fees и увеличить allocation в лучшие сделки."},
{l:5,title:"Fund of Funds",subtitle:"Структуры",body:"Фонд, инвестирующий в другие PE-фонды. Диверсификация + доступ к top-tier фондам. Дополнительный слой комиссий.",example:"FoF $500M → инвестирует в 15-20 PE-фондов\nДиверсификация по стратегиям, географиям, vintage years\nДоп. комиссия: 0.5-1% + 5-10% carry",tip:"Двойной слой комиссий снижает net returns. Но для маленьких LP это единственный доступ к PE."},
{l:5,title:"GP-Led Secondary",subtitle:"Продвинутые структуры",body:"GP создаёт continuation vehicle для удержания портфельной компании дольше. LP могут продать или перейти в новый фонд.",example:"Фонд заканчивается, но компания растёт\n→ GP создаёт continuation fund\n→ Существующие LP: sell @ $X или roll-over\n→ Новые LP входят в continuation",tip:"Самый быстрорастущий сегмент secondary рынка. Решает проблему forced exit."},
{l:5,title:"NAV Lending",subtitle:"Финансирование",body:"Кредит фонду под залог NAV портфеля. Используется для финансирования add-ons, дивидендов, bridge financing.",example:"Фонд NAV $2B → NAV loan $400M (20% LTV)\nИспользование: add-on acquisition для портфельной компании\nОбеспечение: доли в портфельных компаниях",tip:"Спорная практика: увеличивает скрытый leverage фонда. LP всё чаще требуют раскрытия."},
],

// ═══════════════════════════════════════════
// COMMERCIAL BANKING
// ═══════════════════════════════════════════
cb: [
{l:1,title:"Что такое коммерческий банк?",subtitle:"Введение",body:"Принимает вклады, выдаёт кредиты, проводит платежи. Зарабатывает на разнице процентных ставок (NIM) и комиссиях.",example:"Принял вклад под 5% → Выдал кредит под 12%\nNIM = 12% - 5% = 7% — чистый процентный доход",tip:"Коммерческий банк ≠ инвестиционный. Коммерческий работает с депозитами и кредитами."},
{l:1,title:"Депозиты",subtitle:"Пассивные операции",body:"Основной источник фондирования банка. Текущие счета (до востребования), срочные вклады, сберегательные счета.",example:"Текущий счёт: 0-2% — клиент может снять в любой момент\nВклад 1 год: 8-10% — деньги заморожены\nНакопительный: 4-6% — частичный доступ",tip:"CASA ratio (Current Account + Savings Account) — чем выше, тем дешевле фондирование банка."},
{l:1,title:"Кредитование",subtitle:"Активные операции",body:"Основной источник дохода банка. Виды: потребительские, ипотечные, корпоративные, МСБ, овердрафт.",example:"Корпоративный кредит:\nСумма: $10M, Ставка: 10%, Срок: 3 года\nОбеспечение: недвижимость (LTV 70%)\nПроцентный доход банку: ~$3M за 3 года",tip:"5C's of Credit: Character, Capacity, Capital, Collateral, Conditions."},
{l:1,title:"Платёжные операции",subtitle:"Расчёты",body:"Переводы между счетами, банками, странами. SWIFT для международных, местные системы для внутренних платежей.",example:"Внутренний перевод: мгновенно, бесплатно\nSWIFT перевод: 1-3 дня, комиссия $15-50\nАккредитив (L/C): гарантия оплаты в торговле",tip:"KYC (Know Your Customer) и AML (Anti-Money Laundering) — обязательны для каждого платежа."},
{l:2,title:"NIM (Net Interest Margin)",subtitle:"Ключевая метрика",body:"Чистая процентная маржа — разница между процентными доходами и расходами, делённая на средние активы.",example:"Процентные доходы: $500M\nПроцентные расходы: $300M\nСредние активы: $10B\nNIM = ($500M - $300M) / $10B = 2%",tip:"NIM 2-4% — норма для развитых рынков. Выше 5% — развивающиеся рынки или рискованный портфель."},
{l:2,title:"NPL (Non-Performing Loans)",subtitle:"Качество активов",body:"Проблемные кредиты — просрочка 90+ дней. NPL ratio = NPL / Total Loans. Ключевой индикатор здоровья банка.",example:"Кредитный портфель: $5B\nNPL: $250M\nNPL ratio = 5%\nРезервы (provisions): $200M\nCoverage ratio = 200/250 = 80%",tip:"NPL ratio < 3% — хорошо. > 5% — проблемы. Coverage ratio > 100% — банк полностью зарезервирован."},
{l:2,title:"Достаточность капитала (CAR)",subtitle:"Регулирование",body:"Capital Adequacy Ratio = Капитал / RWA (Risk-Weighted Assets). Минимум по Basel III: 8% (Tier 1) + буферы.",example:"Капитал банка: $2B\nRWA: $20B\nCAR = 2/20 = 10%\nМинимум Tier 1: 6% + буфер 2.5% = 8.5%\n→ Банк соответствует требованиям",tip:"RWA: гос. облигации = 0% веса, ипотека = 35%, корп. кредит = 100%. Чем рискованнее — тем больше капитала."},
{l:2,title:"Trade Finance",subtitle:"Торговое финансирование",body:"Инструменты для международной торговли: аккредитивы (L/C), гарантии, инкассо, факторинг.",example:"Импортёр в РФ покупает товар в Китае:\n1. Банк открывает L/C в пользу экспортёра\n2. Экспортёр отгружает, предоставляет документы\n3. Банк проверяет документы → оплачивает\n4. Импортёр возмещает банку",tip:"L/C снижает риск для обеих сторон: экспортёр уверен в оплате, импортёр — в отгрузке."},
{l:3,title:"ALM (Asset-Liability Management)",subtitle:"Управление балансом",body:"Управление разрывом между сроками активов и пассивов. Банк привлекает короткие деньги, выдаёт длинные кредиты.",example:"Депозиты (пассивы): средний срок 6 месяцев\nКредиты (активы): средний срок 3 года\nGap = -2.5 года → процентный риск",tip:"Duration gap анализ помогает оценить чувствительность NII к изменению ставок."},
{l:3,title:"Провизии (Provisions)",subtitle:"Резервы",body:"Банк создаёт резервы на возможные потери по кредитам. IFRS 9 требует ECL (Expected Credit Loss) с момента выдачи.",example:"Stage 1: 12-month ECL (нормальный кредит)\nStage 2: Lifetime ECL (значительный рост риска)\nStage 3: Lifetime ECL (дефолт, NPL)",tip:"Рост провизий = падение прибыли. Банки могут «управлять» прибылью через темп создания резервов."},
{l:3,title:"Correspondent Banking",subtitle:"Межбанковские связи",body:"Банки-корреспонденты проводят платежи в валютах, где у банка нет прямого доступа. NOSTRO/VOSTRO счета.",example:"АИБ (Москва) → корр. счёт в Deutsche Bank (EUR)\nNostro: наш счёт в ИХ банке\nVostro: ИХ счёт в НАШЕМ банке\nSwift MT103 → через цепочку корреспондентов",tip:"De-risking: крупные банки закрывают корр. счета из-за compliance рисков. Критичная проблема."},
{l:3,title:"KYC / AML / Compliance",subtitle:"Комплаенс",body:"Know Your Customer — идентификация клиента. AML — противодействие отмыванию. Обязательно для всех операций.",example:"KYC: паспорт + подтверждение адреса + источник средств\nAML: мониторинг транзакций, sanctions screening\nSTR: отчёт о подозрительной транзакции",tip:"Штрафы за нарушения AML — миллиарды $. HSBC: $1.9B (2012), Deutsche Bank: $630M (2017)."},
{l:4,title:"RAROC",subtitle:"Risk-Adjusted Return",body:"Risk-Adjusted Return on Capital — прибыль с учётом риска, делённая на экономический капитал. Для ценообразования кредитов.",example:"Кредит $10M, маржа 3%, EL 0.5%, OpEx 0.5%\nNet income = $200K\nEconomic capital = $1M\nRAROC = 200K/1M = 20%",tip:"RAROC позволяет сравнивать прибыльность кредитов с разным риском на единой основе."},
{l:4,title:"Liquidity Coverage Ratio (LCR)",subtitle:"Ликвидность",body:"HQLA / Net Cash Outflows (30 дней) ≥ 100%. Банк должен пережить 30-дневный стресс без внешней помощи.",example:"HQLA (гос. облигации + кэш): $5B\nNet outflows за 30 дней: $4B\nLCR = 5/4 = 125% → выполняется",tip:"HQLA: Level 1 (кэш, гос. бонды) = 100%, Level 2A (корп. бонды AA-) = 85%, Level 2B = 50%."},
{l:4,title:"Internal Ratings",subtitle:"Кредитный анализ",body:"Банк разрабатывает внутреннюю рейтинговую систему для оценки PD (вероятности дефолта) заёмщиков. Валидируется регулятором.",example:"Рейтинг 1: PD 0.03% (суверенный)\nРейтинг 4: PD 0.5% (надёжный корпорат)\nРейтинг 7: PD 5% (рискованный МСБ)\nРейтинг 10: дефолт",tip:"IRB Approach (Basel): банк использует свои модели PD, LGD, EAD для расчёта RWA."},
{l:4,title:"Stress Testing",subtitle:"Управление рисками",body:"Моделирование влияния кризисных сценариев на капитал, ликвидность и прибыль банка. Требование регулятора.",example:"Сценарий: ВВП -5%, ставки +300bps, курс -30%\nВлияние на банк:\n- NPL ratio: 3% → 8%\n- Provisions: +$500M\n- CAR: 12% → 9.5%\n→ Банк выживает, но с минимальным запасом",tip:"Обратный стресс-тест: при каком сценарии банк НЕ выживает? Самый ценный insights."},
{l:5,title:"IFRS 9 — ECL Models",subtitle:"Моделирование",body:"Expected Credit Loss модели: PD × LGD × EAD с учётом макроэкономических сценариев. Определяют размер провизий.",example:"PD (Probability of Default): 2%\nLGD (Loss Given Default): 40%\nEAD (Exposure at Default): $10M\nECL = 2% × 40% × $10M = $80K",tip:"Три макро-сценария с весами: base (40%), optimistic (30%), pessimistic (30%)."},
{l:5,title:"Interest Rate Risk in Banking Book",subtitle:"IRRBB",body:"Риск изменения NII и Economic Value при сдвиге процентных ставок. Basel требует 6 сценариев для Banking Book.",example:"Parallel shift +200bps:\n- NII impact: -$50M (депозиты переоцениваются быстрее кредитов)\n- EVE impact: -$200M\n→ Необходим hedging через IRS",tip:"Repricing gap, Duration gap, NII simulation, EVE sensitivity — четыре метода измерения IRRBB."},
{l:5,title:"Treasury Operations",subtitle:"Казначейство",body:"Управление ликвидностью, FX-позицией, портфелем ценных бумаг, process funding для бизнес-линий. Центр ALM.",example:"Утро: проверка NOSTRO-позиций\n→ FX spot/forward для покрытия\n→ Размещение excess liquidity в overnight\n→ Мониторинг LCR/NSFR в реальном времени",tip:"Treasury P&L = часть доходов банка. Но главная роль — управление рисками, не трейдинг."},
{l:5,title:"Resolution Planning",subtitle:"Регулирование",body:"План действий при банкротстве банка. TLAC/MREL — минимум обязательств для bail-in. Living will — план разрешения.",example:"Иерархия bail-in:\n1. Equity → списание\n2. AT1 → конвертация в equity\n3. Tier 2 → конвертация\n4. Senior unsecured → haircut\nЦель: рекапитализация без денег налогоплательщиков",tip:"SRB (EU) и FDIC (US) — органы, ответственные за resolution. Too big to fail → too big to bail."},
],

};

// Export for use
if (typeof module !== 'undefined') module.exports = CARDS_DB;
