// Supplementary cards - loaded after main cards-data.js
// Adds ~80 cards per underrepresented topic

const CARDS_EXTRA = {

english: [
{l:1,title:"to be (am/is/are)",subtitle:"Глагол 'быть'",body:"В русском языке «быть» в настоящем времени опускается, в английском — обязателен. I am, you are, he/she/it is, we/they are.",example:"I am a banker. (Я — банкир)\nShe is busy. (Она занята)\nThey are in a meeting. (Они на встрече)",tip:"Сокращения: I'm, you're, he's, she's, we're, they're — используйте в разговоре."},
{l:1,title:"do / does в вопросах",subtitle:"Вспомогательные глаголы",body:"Для вопросов и отрицаний в Present Simple нужен do/does. Does для he/she/it. Основной глагол без -s.",example:"Do you work here? (не: Work you here?)\nDoes she speak English?\nI don't understand. He doesn't know.",tip:"С to be вспомогательный не нужен: Are you ready? (не: Do you be ready?)"},
{l:1,title:"Предлоги времени",subtitle:"in / on / at",body:"at — точное время и праздники. on — дни и даты. in — месяцы, годы, части дня (кроме at night).",example:"at 3 PM, at Christmas, at the moment\non Monday, on July 5th, on my birthday\nin January, in 2024, in the morning",tip:"In the morning/afternoon/evening, НО at night — исключение!"},
{l:1,title:"Countable vs Uncountable",subtitle:"Исчисляемые/Неисчисляемые",body:"Исчисляемые: a report, two meetings. Неисчисляемые: money, information, advice — без a/an и без множественного числа.",example:"I need information. (не: informations)\nCan I give you some advice?\nHow much money? How many dollars?",tip:"much + uncountable (much time). many + countable (many reports). a lot of — универсально."},
{l:1,title:"Possessive 's",subtitle:"Притяжательный падеж",body:"'s показывает принадлежность для людей и организаций. Для предметов используйте of.",example:"John's report — отчёт Джона\nthe company's policy — политика компании\nthe end of the year (не: the year's end)",tip:"s' для множественного: employees' benefits (льготы сотрудников)."},
{l:2,title:"Past Simple vs Present Perfect",subtitle:"Прошедшее время",body:"Past Simple — завершённое действие в прошлом (yesterday, last week). Present Perfect — связь с настоящим (already, yet, ever).",example:"I sent the email yesterday. (Past Simple)\nI have already sent the email. (Present Perfect)\nDid you finish? vs Have you finished?",tip:"Американцы чаще используют Past Simple даже с already/just/yet."},
{l:2,title:"Passive Voice",subtitle:"Страдательный залог",body:"be + V3 (past participle). Используется когда важнее действие, чем деятель. Очень часто в бизнесе и финансах.",example:"The report was submitted. (Отчёт был подан)\nPayments are processed daily.\nThe deal has been closed.",tip:"By + agent если нужно указать кто: The report was prepared by our team."},
{l:2,title:"Modal Verbs",subtitle:"Модальные глаголы",body:"can (могу), must (должен), should (следует), may (можно), might (возможно), would (бы). Без to после них.",example:"You should check the figures.\nThis may affect the timeline.\nWe must submit by Friday.\nCould you send me the file?",tip:"must = сильная обязанность, should = рекомендация, could = вежливая просьба."},
{l:2,title:"Gerund vs Infinitive",subtitle:"Грамматика",body:"Некоторые глаголы требуют -ing (enjoy, consider, avoid), другие — to (want, need, decide). Некоторые — оба.",example:"I enjoy working with data.\nI want to finish the project.\nI stopped to check (остановился чтобы) vs I stopped checking (перестал проверять)",tip:"After prepositions always -ing: interested in learning, good at presenting."},
{l:2,title:"Used to / Would",subtitle:"Привычки в прошлом",body:"Used to — привычка в прошлом, которой больше нет. Would — только для повторяющихся действий (не состояний).",example:"I used to work in consulting. (не: I would work)\nWe would meet every Monday. = We used to meet...\nI used to be shy. (не: I would be shy)",tip:"Be used to + -ing = привычен к чему-то СЕЙЧАС: I'm used to working late."},
{l:3,title:"Third Conditional",subtitle:"Условные предложения",body:"If + Past Perfect → would have + V3. Нереальное условие в ПРОШЛОМ — сожаление или анализ что было бы если.",example:"If we had closed earlier, we would have avoided the loss.\nIf I had known, I wouldn't have agreed.\nHad we acted sooner, the outcome would have been different.",tip:"Had + S (инверсия) заменяет if в формальном стиле: Had I known = If I had known."},
{l:3,title:"Relative Clauses",subtitle:"Относительные придаточные",body:"Defining: без запятых, необходимая информация. Non-defining: с запятыми, дополнительная. Who/which/that/whose/where.",example:"The analyst who prepared the report is here. (defining)\nJohn, who joined last year, leads the team. (non-defining)\nThe company whose shares dropped...",tip:"В defining clauses that может заменить who/which. В non-defining — нет: John, that... ✗"},
{l:3,title:"Wish / If only",subtitle:"Сожаления",body:"wish + Past Simple — о настоящем. wish + Past Perfect — о прошлом. wish + would — раздражение/просьба об изменении.",example:"I wish I spoke Japanese. (не говорю, но хотел бы)\nI wish I had studied harder. (не учился, жалею)\nI wish they would respond faster.",tip:"If only = wish, но эмоциональнее: If only I had known!"},
{l:3,title:"Emphasis with do/does/did",subtitle:"Усиление",body:"Do/does/did перед глаголом для эмфатического утверждения. Часто в спорах, уточнениях, formal writing.",example:"I do understand your concern. (Я ДЕЙСТВИТЕЛЬНО понимаю)\nShe does have experience in M&A.\nWe did send the documents on time.",tip:"В formal writing: 'The data does suggest...' — мягкое усиление без hedging."},
{l:4,title:"Cleft Sentences",subtitle:"Выделительные конструкции",body:"It is/was... that/who — для выделения части предложения. What... is/was — для выделения темы.",example:"It was the CFO who approved the deal.\n(не кто-то другой, а именно CFO)\nWhat we need is a clear strategy.\nWhat concerns me is the timeline.",tip:"Cleft sentences помогают управлять фокусом внимания слушателя в презентациях."},
{l:4,title:"Discourse Markers",subtitle:"Связность речи",body:"Слова-связки для презентаций: having said that, that being said, on that note, to that end, by the same token.",example:"Revenue grew 15%. Having said that, margins contracted.\nWe need to cut costs. To that end, we're restructuring.\nOn a related note, the board approved the budget.",tip:"Не начинайте каждое предложение с However/Moreover — варьируйте. 1-2 на абзац максимум."},
{l:4,title:"Participle Clauses",subtitle:"Причастные обороты",body:"Сокращённые придаточные через -ing (активное) или -ed (пассивное). Формальный стиль, отчёты.",example:"Having analyzed the data, we recommend... (= After we analyzed)\nConsidered too risky, the deal was rejected. (= Because it was considered)\nBased in London, the firm operates globally.",tip:"Dangling participle — частая ошибка: 'Walking to work, the report was finished.' ✗ (кто шёл?)"},
{l:5,title:"Subjunctive in Formal Writing",subtitle:"Сослагательное в документах",body:"Формальный subjunctive: глагол в base form после suggest, recommend, insist, demand, it is essential/vital/imperative.",example:"The committee recommends that the policy be revised.\nIt is imperative that every branch comply with regulations.\nWe insist that the payment be made immediately.",tip:"Были vs be: 'If I were...' (subjunctive) vs 'If I was...' (informal). В документах — were."},
{l:5,title:"Mixed Conditionals",subtitle:"Смешанные условные",body:"Комбинируют Type 2 и 3: Past → Present (If + Past Perfect, would + V) или Present → Past (If + Past, would have + V3).",example:"If I had studied finance, I would be a banker now.\n(прошлое условие → настоящий результат)\nIf she were more careful, she wouldn't have made that error.\n(настоящее качество → прошлый результат)",tip:"Mixed conditionals показывают C2-уровень. Используйте осознанно, не для красоты."},
],

japanese: [
{l:1,title:"数字 (すうじ) — Числа",subtitle:"suuji — Числительные",body:"1-10 по-японски: いち、に、さん、し/よん、ご、ろく、しち/なな、はち、きゅう/く、じゅう.",example:"100 = ひゃく (hyaku)\n1000 = せん (sen)\n10000 = まん (man)\n1万円 = 10,000 иен",tip:"В Японии считают не тысячами, а десятками тысяч: 100万 = 1,000,000 (百万 hyaku-man)."},
{l:1,title:"すみません",subtitle:"Sumimasen — Извините",body:"Универсальное слово: извините, простите, спасибо (за беспокойство), привлечение внимания. Одно из самых полезных слов.",example:"すみません、駅はどこですか？\nSumimasen, eki wa doko desu ka?\nИзвините, где станция?",tip:"ごめんなさい (gomen nasai) — извините (за вину). すみません — более универсальное."},
{l:1,title:"Частицы を (wo) и に (ni)",subtitle:"Базовые частицы",body:"を — показывает объект действия (что делаем). に — направление, время, получатель.",example:"コーヒーを飲みます。Koohii wo nomimasu. (Пью кофе — を = что)\n東京に行きます。Toukyou ni ikimasu. (Еду в Токио — に = куда)\n3時に会います。3-ji ni aimasu. (Встретимся в 3 — に = когда)",tip:"に для конкретного времени (3時に), но не для relative time: 今日は (kyou wa) — без に."},
{l:1,title:"これ / それ / あれ",subtitle:"Указательные",body:"これ — это (рядом со мной). それ — то (рядом с вами). あれ — то (далеко от обоих). Базовая система ко-со-а.",example:"これは何ですか？(Kore wa nan desu ka?) — Что это?\nそれをください。(Sore wo kudasai.) — Дайте мне то.\nあれは東京タワーです。— То — Токийская башня.",tip:"この/その/あの + существительное: この本 (kono hon) = эта книга."},
{l:2,title:"ない-форма (Отрицание)",subtitle:"nai-form",body:"Отрицательная форма глаголов. Для Group 1: u→anai. Group 2: убрать る, +ない. する→しない, くる→こない.",example:"行く→行かない (ikanai — не идти)\n食べる→食べない (tabenai — не есть)\n分かる→分からない (wakaranai — не понимать)",tip:"ません — вежливое отрицание: 分かりません (wakarimasen). ない — plain form."},
{l:2,title:"~たい (хочу)",subtitle:"tai-form — Желание",body:"ます-основа + たい = хочу (сделать). Используется только для СВОИХ желаний, не чужих.",example:"日本に行きたい。Nihon ni ikitai. (Хочу поехать в Японию)\n寿司が食べたい。Sushi ga tabetai. (Хочу суши)\n何が飲みたいですか？(Что хотите выпить?)",tip:"Для чужих желаний: ~たがっている (tagatteiru) или 欲しい (hoshii) для предметов."},
{l:2,title:"から / ので (потому что)",subtitle:"Причинные союзы",body:"から — прямая причина, более субъективная. ので — мягче, объективнее, вежливее. В бизнесе чаще ので.",example:"忙しいから、行けません。(Занят, поэтому не могу пойти — から)\n会議があるので、失礼します。(Так как встреча, я откланяюсь — ので, вежливее)",tip:"ので после na-прилагательных и существительных: 静かなので (shizuka na node)."},
{l:2,title:"~ている (Progressive)",subtitle:"Длящееся действие",body:"て-форма + いる = действие в процессе, результат, привычка. Аналог Present Continuous.",example:"今、食べている。Ima, tabete iru. (Сейчас ем)\n東京に住んでいる。Toukyou ni sunde iru. (Живу в Токио)\n結婚している。Kekkon shite iru. (Женат/замужем — результат)",tip:"知っている (shitte iru — знаю), но 知らない (shiranai — не знаю, не 知っていない)."},
{l:3,title:"受身形 (Пассив)",subtitle:"ukemikei — Страдательный залог",body:"Group 1: u→areru. Group 2: る→られる. Используется для неудобных ситуаций (meiwaku passive).",example:"先生に褒められた。Sensei ni homerareta. (Учитель похвалил — приятный пассив)\n雨に降られた。Ame ni furareta. (Попал под дождь — meiwaku passive)\n部長に呼ばれた。Buchou ni yobareta. (Меня вызвал начальник)",tip:"Meiwaku passive — уникальная японская конструкция: пассив для ситуаций, которые причинили неудобство."},
{l:3,title:"使役形 (Каузатив)",subtitle:"shieki-kei — Побуждение",body:"«Заставить/позволить делать». Group 1: u→aseru. Group 2: る→させる. する→させる, くる→こさせる.",example:"部下にレポートを書かせた。\nBuka ni repooto wo kakaseta.\n(Заставил подчинённого написать отчёт)\n\n行かせてください。Ikasete kudasai.\n(Позвольте мне пойти)",tip:"させていただく — сверхвежливая форма: 説明させていただきます (Позвольте объяснить)."},
{l:3,title:"Частица よ / ね / よね",subtitle:"Эмоциональные частицы",body:"よ — утверждение (новая информация для собеседника). ね — согласие (подтверждение). よね — мягкое утверждение.",example:"明日は休みだよ。(Завтра выходной! — ты не знал?)\n今日は暑いですね。(Сегодня жарко, правда?)\nこれ、美味しいよね。(Это вкусно, правда ведь?)",tip:"В бизнесе ね — важный инструмент rapport: そうですね (sou desu ne — да, верно)."},
{l:4,title:"条件形 (Условие)",subtitle:"jouken-kei — ば/たら/と/なら",body:"4 способа сказать «если» в японском. Каждый имеет нюансы использования.",example:"ば (ba): 安ければ買います。(Если дёшево, куплю — общее условие)\nたら (tara): 着いたら電話します。(Когда приеду, позвоню — временная последовательность)\nと (to): ボタンを押すとドアが開く。(Нажмёшь кнопку — дверь откроется — автоматическое следствие)\nなら (nara): 日本に行くなら、京都がいい。(Если едешь в Японию, Киото хорош — совет)",tip:"たら — самый универсальный. Если не уверены — используйте たら."},
{l:4,title:"N1/N2 Грамматика: ~わけ",subtitle:"Продвинутые конструкции",body:"わけ = причина/смысл. ~わけではない (не значит что), ~わけにはいかない (не могу позволить себе).",example:"嫌いなわけではない。(Не то чтобы мне не нравилось)\nサボるわけにはいかない。(Не могу позволить себе прогулять)\nそういうわけで、辞めました。(Поэтому я уволился)",tip:"わけ — один из маркеров продвинутого уровня. Часто на JLPT N2."},
{l:5,title:"敬語の使い分け",subtitle:"Нюансы кэйго",body:"Правильный выбор между 尊敬語 и 謙譲語 в зависимости от контекста — ключевой навык делового японского.",example:"Звонок клиенту:\n「田中様はいらっしゃいますか。」(尊敬語 — о клиенте)\n「佐藤が申し上げた通り...」(謙譲語 — о своём коллеге)\n「後ほどお電話させていただきます。」(謙譲語 — о себе)",tip:"О СВОЕЙ компании и коллегах — всегда 謙譲語. О клиенте/партнёре — всегда 尊敬語."},
],

ib: [
{l:1,title:"Equity vs Debt",subtitle:"Виды капитала",body:"Equity — собственный капитал (акции), владельцы несут риск и получают прибыль. Debt — заёмный (облигации, кредиты), фиксированные выплаты.",example:"Equity: купил акцию за $100, цена выросла до $150 = +50%\nDebt: купил облигацию за $100, получаешь 5% = $5/год",tip:"Equity дороже Debt для компании (акционеры требуют больший return), но не обязательно к выплате."},
{l:1,title:"P&L (Income Statement)",subtitle:"Финансовая отчётность",body:"Отчёт о прибылях и убытках. Показывает доходы, расходы и прибыль за период. Top-line = Revenue, Bottom-line = Net Income.",example:"Revenue: $500M\n- COGS: $200M\n= Gross Profit: $300M\n- OpEx: $150M\n= EBIT: $150M\n- Interest: $20M\n- Tax: $32M\n= Net Income: $98M",tip:"Gross Margin = GP/Revenue. Operating Margin = EBIT/Revenue. Net Margin = NI/Revenue."},
{l:1,title:"Balance Sheet",subtitle:"Финансовая отчётность",body:"Баланс: Assets = Liabilities + Equity. Показывает что компания имеет, кому должна и сколько принадлежит акционерам.",example:"Assets: Cash $50M + PPE $200M + Receivables $80M = $330M\nLiabilities: Debt $150M + Payables $30M = $180M\nEquity: $150M\nAssets = Liabilities + Equity ✓",tip:"Working Capital = Current Assets - Current Liabilities. Отрицательный WC может быть нормой (Amazon)."},
{l:2,title:"Мультипликаторы",subtitle:"Относительная оценка",body:"Коэффициенты для сравнения компаний: P/E, EV/EBITDA, EV/Revenue, P/B. Показывают сколько рынок платит за единицу метрики.",example:"P/E = Цена акции / EPS = сколько лет окупается\nEV/EBITDA = Enterprise Value / EBITDA\nP/B = Price / Book Value",tip:"High multiple = рынок ожидает рост. Low multiple = дёшево или проблемы."},
{l:2,title:"Free Cash Flow (FCF)",subtitle:"Денежный поток",body:"Свободный денежный поток — деньги, доступные для выплаты инвесторам после всех операционных расходов и капитальных затрат.",example:"EBITDA: $100M\n- Taxes: $20M\n- CapEx: $25M\n- Change in WC: $5M\n= FCF: $50M\n= Unlevered FCF (до процентов по долгу)",tip:"FCF = реальные деньги. Прибыль = бухгалтерская метрика. Компания может быть прибыльной, но без FCF."},
{l:2,title:"Beta (β)",subtitle:"CAPM",body:"Мера систематического риска акции относительно рынка. β=1 — как рынок, β>1 — волатильнее, β<1 — стабильнее.",example:"β = 1.2 → рынок вырос 10% → акция ~12%\nRe = Rf + β × (Rm - Rf)\nRe = 4% + 1.2 × 6% = 11.2%",tip:"Levered β включает эффект долга. Unlevered β (asset β) — чистый бизнес-риск."},
{l:3,title:"Synergies",subtitle:"M&A",body:"Дополнительная стоимость от объединения. Cost synergies (сокращение дублирующих расходов) и Revenue synergies (кросс-продажи).",example:"Cost: объединение back-office = -$50M расходов/год\nRevenue: кросс-продажи клиентам обеих компаний = +$30M\nPV of synergies = $500M → оправдывает премию",tip:"Cost synergies реализуются на 80%+, revenue — на 30-50%. Покупатели часто переоценивают synergies."},
{l:3,title:"Capital Structure",subtitle:"Структура капитала",body:"Соотношение Debt и Equity в финансировании компании. Оптимальная структура минимизирует WACC.",example:"Conservative: 20% Debt / 80% Equity\nOptimal: 40% Debt / 60% Equity (мин. WACC)\nAggressive: 70% Debt / 30% Equity (LBO)\nNet Debt/EBITDA = 2-3x — нормальный leverage",tip:"Trade-off: Debt дешевле (налоговый щит), но увеличивает риск банкротства."},
{l:4,title:"Football Field Chart",subtitle:"Оценка — визуализация",body:"График, показывающий диапазоны оценки из разных методов. Стандарт IB-презентаций.",example:"DCF: $800M - $1,100M\nTrading Comps: $750M - $950M\nPrecedent Transactions: $900M - $1,200M\n52-week Range: $650M - $1,000M\n→ Fair value range: $850M - $1,050M",tip:"Пересечение диапазонов = наиболее вероятная справедливая стоимость."},
{l:4,title:"Оценка: Сценарный анализ",subtitle:"Sensitivity Analysis",body:"Таблица чувствительности показывает как меняется оценка при изменении ключевых допущений (WACC, growth, exit multiple).",example:"     WACC:  8%    9%    10%\nGrowth 2%: $1.2B  $1.0B  $0.9B\nGrowth 3%: $1.5B  $1.2B  $1.0B\nGrowth 4%: $1.9B  $1.5B  $1.2B",tip:"Sensitivity table — обязательный слайд в любом DCF. Показывает robustness оценки."},
{l:5,title:"Contribution Analysis",subtitle:"Merger Analysis",body:"Сравнивает вклад каждой компании в combined entity по Revenue, EBITDA, Assets. Определяет справедливое ownership split.",example:"Company A: Revenue 60%, EBITDA 55%\nCompany B: Revenue 40%, EBITDA 45%\n→ A shareholders get ~57% of combined entity\n→ Negotiation range: 55-60%",tip:"Если contribution > ownership → сделка dilutive для этой стороны. Ключевой аргумент в переговорах."},
],

pe: [
{l:1,title:"Жизненный цикл PE-фонда",subtitle:"Структура",body:"PE-фонд живёт 10-12 лет: 1-5 год — инвестиционный период (покупки), 5-10 год — управление и выходы.",example:"Год 1-2: fundraising + first deals\nГод 3-5: основные инвестиции\nГод 5-7: улучшение портфельных компаний\nГод 7-10: exits (продажи)\nГод 10-12: ликвидация",tip:"Capital calls идут в первые 5 лет — LP должны держать liquidity для ответа на calls."},
{l:1,title:"Exit стратегии",subtitle:"Выход из инвестиций",body:"Три основных способа выхода: Trade Sale (продажа стратегу), Secondary (продажа другому PE), IPO (выход на биржу).",example:"Trade Sale: PE продаёт компанию корпорации\nSecondary: PE продаёт другому PE-фонду\nIPO: PE выводит компанию на биржу\nDividend Recap: компания берёт долг → платит дивиденд PE",tip:"Trade Sale — самый частый exit (~60%). IPO — самый громкий, но не самый частый (~10%)."},
{l:2,title:"Fund Terms",subtitle:"Условия фонда",body:"LPA (Limited Partnership Agreement) определяет: management fee, carry, hurdle rate, clawback, key man clause.",example:"Management fee: 2% committed capital\nCarried interest: 20% over 8% hurdle\nClawback: GP возвращает excess carry\nKey man: если ключевой партнёр уходит, инвестирование приостанавливается",tip:"GP commit (1-5% фонда) — skin in the game. LP всё чаще требуют 3%+."},
{l:2,title:"Due Diligence в PE",subtitle:"Анализ сделки",body:"Всесторонняя проверка перед покупкой: financial, commercial, legal, tax, IT, management, ESG. Занимает 6-12 недель.",example:"Financial DD: Quality of Earnings (QoE)\nCommercial DD: рынок, конкуренция, клиенты\nManagement DD: оценка топ-менеджмента\nIT DD: системы, tech debt\nESG DD: экология, социальная ответственность",tip:"Quality of Earnings — самый важный. Вычищает non-recurring items и нормализует EBITDA."},
{l:3,title:"Operating Partners",subtitle:"Создание стоимости",body:"Бывшие CEO/COO/CFO, работающие в PE-фонде для операционного улучшения портфельных компаний.",example:"Operating Partner работает с CEO портфельной компании:\n- Pricing optimization: +$5M EBITDA\n- Procurement centralization: +$3M\n- Sales force effectiveness: +$7M\n→ Total value creation: +$15M EBITDA",tip:"Top PE-фонды (KKR Capstone, Bain Portfolio Group) выделяют operating teams как конкурентное преимущество."},
{l:3,title:"Capital Call & Distribution",subtitle:"Cash Flows LP",body:"Capital Call — GP запрашивает деньги у LP для инвестиции. Distribution — GP возвращает деньги при exit.",example:"Commitment: $50M\nYear 1: Capital Call $10M (20%)\nYear 2: Capital Call $15M (30%)\nYear 5: Distribution $20M (exit #1)\nYear 7: Distribution $80M (remaining exits)\n→ Net MOIC: 2.0x, IRR: ~15%",tip:"LP получают обратно деньги неравномерно — J-curve effect. Планируйте ликвидность."},
{l:4,title:"LBO Model — подробно",subtitle:"Финансовое моделирование",body:"Полная LBO модель: Sources & Uses, Operating Model (5 лет), Debt Schedule, Credit Metrics, Returns Analysis.",example:"Sources: Equity $300M, Term Loan $400M, Mezzanine $100M\nUses: Purchase $750M, Fees $50M\n\nYear 1-5: EBITDA grows 10→15%/yr\nDebt paydown: $400M → $200M\nExit at 8x EBITDA → Equity value $700M\nIRR: 18.5%, MOIC: 2.3x",tip:"Sponsors care about: entry multiple, leverage, margin expansion, FCF conversion, exit multiple."},
{l:4,title:"Distressed PE",subtitle:"Стратегии",body:"Инвестиции в проблемные компании/долги. Покупка долга со скидкой (40-60 cents/$), конвертация в equity при реструктуризации.",example:"Компания в Chapter 11: долг $500M торгуется по $0.30/$1\nPE покупает Senior Debt за $150M\nПосле реструктуризации: получает 60% equity\nCompany recovers → equity worth $400M\nReturn: 2.7x",tip:"Требует глубокого понимания bankruptcy law и credit analysis."},
{l:5,title:"Fund Performance Metrics",subtitle:"Анализ фонда",body:"DPI (Distributions to Paid-In), RVPI (Residual Value), TVPI (Total Value). PME (Public Market Equivalent) для сравнения с индексами.",example:"DPI: $600M / $500M = 1.2x (уже вернул)\nRVPI: $400M / $500M = 0.8x (осталось в портфеле)\nTVPI = DPI + RVPI = 2.0x (total value)\nNet IRR: 18%\nPME vs S&P500 = 1.3x (outperformed by 30%)",tip:"DPI = «cash-on-cash» — реальные деньги. RVPI основан на оценках GP — может быть завышен."},
{l:5,title:"Secondaries Market",subtitle:"Вторичный рынок PE",body:"LP продаёт свою долю в PE-фонде другому инвестору. Рынок $100B+. Цены = discount/premium к NAV.",example:"LP хочет ликвидность:\nNAV доли: $100M\nSecondary buyer предлагает: $90M (10% discount)\nDiscount зависит от: quality, vintage, remaining life\n\nGP-led secondary: GP создаёт continuation vehicle",tip:"Secondaries — самый быстрорастущий сегмент PE. Позволяют LP управлять ликвидностью."},
],

addin: [
{l:1,title:"Пакет анализа (Analysis ToolPak)",subtitle:"Статистика",body:"Набор статистических инструментов: гистограмма, описательная статистика, корреляция, регрессия, t-тест. Встроен, нужно активировать.",example:"Файл → Параметры → Надстройки → Пакет анализа → ОК\nДанные → Анализ данных → выберите инструмент",tip:"Один из самых полезных встроенных add-in. Не требует VBA или программирования."},
{l:1,title:"Надстройка Подстановщик (Solver)",subtitle:"Оптимизация",body:"Решает задачи оптимизации: максимизация прибыли, минимизация затрат при ограничениях. Линейное и нелинейное программирование.",example:"Цель: максимизировать прибыль (ячейка D10)\nИзменяемые: цены (B2:B5)\nОграничения: бюджет ≤ $1M, запас ≥ 0",tip:"Для сложных задач: OpenSolver (open-source) поддерживает больше переменных."},
{l:2,title:"Inquire Add-In",subtitle:"Аудит книг",body:"Анализирует зависимости между книгами, находит ошибки в формулах, сравнивает версии файлов. Для Enterprise Excel.",example:"Inquire → Workbook Analysis → Diagram → показывает связи между листами и книгами\nCell Relationship Diagram — визуализация зависимостей формул",tip:"Доступен только в Office Professional Plus / Microsoft 365 Enterprise."},
{l:2,title:"Fuzzy Lookup",subtitle:"Нечёткий поиск",body:"Бесплатная надстройка от Microsoft Research. Находит приблизительные совпадения в таблицах. Идеально для matching.",example:"Таблица A: 'Газпром нефть'\nТаблица B: 'ПАО Газпром Нефть'\nFuzzy Lookup: совпадение 0.85 → match!",tip:"Скачайте с Microsoft Download Center. Работает через вкладку Fuzzy Lookup на ленте."},
{l:3,title:"Power BI Publisher",subtitle:"Интеграция с Power BI",body:"Надстройка для публикации Excel-таблиц и диапазонов прямо в Power BI дашборды. Экспорт данных из Excel в облако.",example:"Выделите таблицу → Power BI → Pin\nТаблица появляется как tile на дашборде\nОбновляется при изменении Excel-файла",tip:"Альтернатива: Power BI Desktop → Get Data → Excel. Но Publisher удобнее для quick sharing."},
{l:3,title:"Office.js API — обзор",subtitle:"Современная платформа",body:"JavaScript API для Office. Работает в Desktop, Online, Mobile. Два подхода: Task Pane (панель) и Custom Functions (формулы).",example:"// Чтение данных:\nExcel.run(async (ctx) => {\n  const range = ctx.workbook.getSelectedRange();\n  range.load('values');\n  await ctx.sync();\n  console.log(range.values);\n});",tip:"Office.js — будущее add-in разработки. VBA/VSTO постепенно уступают."},
{l:4,title:"Spill-Safe Add-In архитектура",subtitle:"Design Patterns",body:"Modern Excel add-in должен корректно работать с Dynamic Arrays (spill ranges). Используйте Excel.Range.getSpillingToRange().",example:"// Обработка spill ranges:\nconst range = sheet.getRange('A1');\nconst spillRange = range.getSpillingToRange();\nspillRange.load('address,values');\nawait ctx.sync();\n// spillRange.address = 'A1:A100'",tip:"Тестируйте add-in с Dynamic Arrays: FILTER, SORT, UNIQUE могут менять размер output."},
{l:4,title:"Sideloading для разработки",subtitle:"Development",body:"Загрузка add-in без публикации в AppSource. Для тестирования и внутренних корпоративных инструментов.",example:"1. Создайте manifest.xml\n2. Shared folder или localhost\n3. Excel → Insert → My Add-ins → Shared Folder\n4. Или: npx office-addin-debugging start",tip:"Windows: \\\\server\\share + Group Policy. Mac: ~/Library/Containers/.../wef/. Online: Admin center."},
{l:5,title:"Excel-DNA + React Task Pane",subtitle:"Гибридная архитектура",body:"Excel-DNA для быстрых XLL-функций + WebView2 Task Pane на React для UI. Лучшее из двух миров.",example:"// Excel-DNA (C#) — быстрые UDF:\n[ExcelFunction] public static double Price(...)\n\n// React Task Pane — rich UI:\n<TaskPane>\n  <PricingTool onCalculate={handleCalc}/>\n</TaskPane>\n\n// Коммуникация через CustomTaskPane + COM",tip:"Эта архитектура используется в банках для pricing add-ins: скорость C# + UI React."},
{l:5,title:"AppSource Certification",subtitle:"Публикация",body:"Процесс сертификации add-in для публикации в Microsoft AppSource. Требования: безопасность, privacy, UX, performance.",example:"Checklist:\n✓ SSL (HTTPS) для всех ресурсов\n✓ Privacy policy URL\n✓ Responsive UI\n✓ Performance < 3s load\n✓ Error handling\n✓ Accessibility (WCAG)\n✓ Multi-language support",tip:"Сертификация занимает 2-4 недели. Частые причины отказа: mixed content (HTTP), отсутствие privacy policy."},
],

cb: [
{l:1,title:"Процентная ставка",subtitle:"Базовые понятия",body:"Цена денег. Ключевая ставка ЦБ определяет стоимость денег в экономике. Банки добавляют маржу поверх ключевой ставки.",example:"Ключевая ставка ЦБ: 10%\nСтавка привлечения (депозит): 8%\nСтавка размещения (кредит): 15%\nМаржа банка: 15% - 8% = 7%",tip:"При росте ключевой ставки дорожают и кредиты и депозиты, но маржа банка может сужаться."},
{l:1,title:"Банковская лицензия",subtitle:"Регулирование",body:"Банк может работать только с лицензией ЦБ. Универсальная — все операции. Базовая — ограниченный перечень. Отзыв = ликвидация.",example:"Универсальная: капитал ≥ 1 млрд ₽\nБазовая: капитал ≥ 300 млн ₽\nМФО: не банк, ограниченные операции\nЛицензия на привлечение вкладов — отдельно",tip:"Проверка лицензии: сайт ЦБ РФ → Реестр кредитных организаций."},
{l:2,title:"Банковские риски",subtitle:"Риск-менеджмент",body:"Основные риски: кредитный (невозврат), рыночный (курсы/ставки), операционный (сбои/мошенничество), ликвидности (нехватка средств).",example:"Кредитный: заёмщик не вернул $10M\nРыночный: курс USD/RUB упал на 10% → потери по FX-позиции\nОперационный: IT-сбой остановил платежи\nЛиквидности: mass withdrawal of deposits",tip:"Basel III определяет минимальные требования капитала для каждого типа риска."},
{l:2,title:"SWIFT и платёжные системы",subtitle:"Расчёты",body:"SWIFT — глобальная система обмена финансовыми сообщениями между 11000+ банками. Не перемещает деньги, а отправляет инструкции.",example:"MT103: единичный клиентский перевод\nMT202: межбанковский перевод\nMT700: аккредитив\nMT940: выписка по счёту\nSWIFT gpi: трекинг платежей в реальном времени",tip:"SWIFT ≠ платёж. SWIFT отправляет СООБЩЕНИЕ. Деньги двигаются через корр. счета."},
{l:3,title:"Credit Scoring",subtitle:"Скоринг",body:"Статистическая модель оценки кредитоспособности. Application scoring (при заявке) и Behavioral scoring (в процессе обслуживания).",example:"Факторы скоринга:\n- Кредитная история: 35%\n- Текущая долговая нагрузка: 25%\n- Стаж и доход: 20%\n- Обеспечение: 10%\n- Прочие: 10%\nScore > 700 → одобрение",tip:"GINI coefficient (0-1) измеряет качество скоринговой модели. Good model: GINI > 0.5."},
{l:3,title:"Валютный контроль",subtitle:"ВЭД",body:"Банк контролирует валютные операции клиентов. Постановка контрактов на учёт, справки о подтверждающих документах.",example:"Контракт > лимита → постановка на учёт в банке\nКаждая операция → справка о подтверждающих документах\nРепатриация валютной выручки\nОтчётность перед ЦБ",tip:"Нарушения валютного законодательства — штрафы до 100% суммы операции."},
{l:4,title:"Transfer Pricing (FTP)",subtitle:"Внутреннее ценообразование",body:"Funds Transfer Pricing — внутренняя трансфертная цена ресурсов. Измеряет вклад каждого подразделения в прибыль банка.",example:"Депозитное подразделение: привлекло депозит 8%, FTP = 10% → маржа 2%\nКредитное подразделение: выдало кредит 14%, FTP = 10% → маржа 4%\nTreasury: управляет разницей",tip:"FTP-кривая привязана к кривой доходности + ликвидностная премия + кредитная премия."},
{l:4,title:"Basel III — Three Pillars",subtitle:"Регулирование",body:"Pillar 1: минимальный капитал (CAR, LCR, NSFR). Pillar 2: надзорный процесс (SREP, ICAAP). Pillar 3: рыночная дисциплина (раскрытие).",example:"Pillar 1: CAR ≥ 8%, LCR ≥ 100%, NSFR ≥ 100%\nPillar 2: банк определяет доп. капитал для своих специфических рисков\nPillar 3: ежеквартальная публикация отчётности",tip:"ICAAP (Internal Capital Adequacy Assessment) — банк сам оценивает нужный капитал."},
{l:5,title:"Open Banking / API Banking",subtitle:"Цифровая трансформация",body:"Банк предоставляет API для сторонних разработчиков. PSD2 (EU) и аналоги обязывают банки открывать данные с согласия клиента.",example:"API Account Info: баланс, транзакции\nAPI Payment Initiation: инициация платежа\nAPI Confirmation of Funds: проверка наличия средств\n\nFintech → Bank API → клиентские данные → инновационный сервис",tip:"BaaS (Banking as a Service): небанковские компании встраивают банковские продукты через API."},
{l:5,title:"Operational Resilience",subtitle:"Непрерывность бизнеса",body:"Способность банка продолжать критические операции при сбоях. Регуляторное требование: Impact Tolerance, mapping, testing.",example:"Critical services:\n1. Payments processing — tolerance: 2 hours\n2. Deposits — tolerance: 4 hours\n3. Lending — tolerance: 24 hours\n\nMapping: people, processes, technology, data, third parties\nTesting: annual scenario exercises",tip:"Post-COVID фокус: cloud resilience, remote work, third-party risk (один облачный провайдер для всех банков)."},
],

};

// Merge into main CARDS_DB
if (typeof CARDS_DB !== 'undefined') {
  Object.entries(CARDS_EXTRA).forEach(([key, cards]) => {
    if (CARDS_DB[key]) {
      CARDS_DB[key].push(...cards);
    } else {
      CARDS_DB[key] = cards;
    }
  });
}
